T115 契約一覧 ソート機能
Lorenzras/yumecoco-monorepo pull request #113
Opened 2023-02-03 07:17 UTC by Lorenzras

## 派生元

- #112 

## 変更

## 変更理由

2023-02-03 07:25 UTC, Lorenzras commented
![](https://github.trello.services/images/mini-trello-icon.png) [T115-契約一覧：項目をクリックすると、その項目順になってほしい](https://trello.com/c/H9dXz6Jf/246-t115-%E5%A5%91%E7%B4%84%E4%B8%80%E8%A6%A7%EF%BC%9A%E9%A0%85%E7%9B%AE%E3%82%92%E3%82%AF%E3%83%AA%E3%83%83%E3%82%AF%E3%81%99%E3%82%8B%E3%81%A8%E3%80%81%E3%81%9D%E3%81%AE%E9%A0%85%E7%9B%AE%E9%A0%86%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%A6%E3%81%BB%E3%81%97%E3%81%84)

2023-02-06 05:10 UTC, RPA02coco requested changes
絞り込み検索の機能で、動作が効かなくなってしまっているようです。
ご確認をお願いいたします。

2023-02-06 06:13 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projContractSearch/parts/WrappedSearchField.tsx
> -
ありがとうございます。 ef4cb535 で 修正しました。確認お願い致します。
移行の時、パッケージのインポートのミスってしまいました。ｗ

2023-02-08 01:58 UTC, RPA02coco approved these changes
修正確認しました。
ご対応ありがとうございます。

2023-02-08 01:58 UTC, merged