T255 行ごとについてもカンマありにしました
Lorenzras/yumecoco-monorepo pull request #117
Opened 2023-02-07 07:22 UTC by Lorenzras

## 変更

- 行ごとについてもカンマありにしました。（ ✕ 1000000　○ 1,000,000）

## 変更理由

- https://trello.com/c/Kgmor3nL

2023-02-07 07:28 UTC, Lorenzras commented
![](https://github.trello.services/images/mini-trello-icon.png) [見積：行ごとについてもカンマありにしたい。（ ✕ 1000000 ○ 1,000,000）](https://trello.com/c/Kgmor3nL/255-%E8%A6%8B%E7%A9%8D%EF%BC%9A%E8%A1%8C%E3%81%94%E3%81%A8%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%E3%82%82%E3%82%AB%E3%83%B3%E3%83%9E%E3%81%82%E3%82%8A%E3%81%AB%E3%81%97%E3%81%9F%E3%81%84%E3%80%82%EF%BC%88-%E2%9C%95-1000000-%E2%97%8B-1000000%EF%BC%89)

2023-02-08 02:46 UTC, RPA02coco requested changes
確認しました。
コメント部分の確認をお願いします。

2023-02-08 02:46 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projEstimate/tables/estimatesVirtual/rowFields/RowUnitPriceBeforeTax.tsx
> +        console.log('fired!');
```console.log```が残ってしまっています。

2023-02-08 23:56 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projEstimate/tables/estimatesVirtual/rowFields/RowUnitPriceBeforeTax.tsx
> +        console.log('fired!');
確認ありがとうございます。 console.log を d41b2639 で削除しました。

2023-02-09 01:00 UTC, RPA02coco approved these changes
修正確認しました。
ご対応ありがとうございます。

2023-02-09 01:00 UTC, merged