請求入力：保存後に請求済金額を更新する
Lorenzras/yumecoco-monorepo pull request #118
Opened 2023-02-08 03:07 UTC by RPA02coco

**変更**
---

- 請求書の保存時に、ブラウザの請求済み金額を更新する

**変更理由**
---

- https://trello.com/c/2KymVN6p

2023-02-13 06:01 UTC, Lorenzras requested changes
確認しました。

保存後、こんな感じになりました。
https://rdmuhwtt6gx7.cybozu.com/k/176/#/project/payment/invoice?invoiceId=64ea049f-88d9-4b2c-8a92-03bea16e4ecd

2023-02-14 01:22 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/api/convertInvoiceToForm.ts
> +    undecidedPaymentDate: !(plannedPaymentDate.value) ? true : false,
ご指摘ありがとうございます。
[```e21272e```](https://github.com/Lorenzras/yumecoco-monorepo/pull/118/commits/e21272e6f48e07b2e0ee0d3f07f6e6d0f308a2ef)にて修正しました。

2023-02-14 01:22 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/api/convertInvoiceToForm.ts
> +    plannedPaymentDate: !(plannedPaymentDate.value) ? '' : String(parseISO(plannedPaymentDate.value)),
ご指摘ありがとうございます。
[```e21272e```](https://github.com/Lorenzras/yumecoco-monorepo/pull/118/commits/e21272e6f48e07b2e0ee0d3f07f6e6d0f308a2ef)にて修正しました。

2023-02-14 04:24 UTC, Lorenzras approved these changes
確認しました。

2023-02-14 04:26 UTC, merged