請求入力
Lorenzras/yumecoco-monorepo pull request #124
Opened 2023-02-09 03:50 UTC by RPA02coco

2023-02-15 07:04 UTC, Lorenzras requested changes
確認しました。挙動に問題ないと思います。

フォルダー名：
- calclation -> calculation

2023-02-17 01:28 UTC, RPA02coco commented on packages/api-kintone/src/invoice/calclation/calculateAmountBeforeTax.ts
> +    }
ご指摘ありがとうございます。
[```6b56b4```](https://github.com/Lorenzras/yumecoco-monorepo/pull/124/commits/6b56b4d9ead2c7b6506a997168485ed833f67e48)にて修正しました。

2023-02-17 01:28 UTC, RPA02coco commented on packages/api-kintone/src/invoice/calclation/calculateAmountBeforeTax.ts
> +    }
ご指摘ありがとうございます。
[```6b56b4```](https://github.com/Lorenzras/yumecoco-monorepo/pull/124/commits/6b56b4d9ead2c7b6506a997168485ed833f67e48)にて修正しました。

2023-02-17 01:30 UTC, RPA02coco commented on packages/api-kintone/src/invoice/calclation/calculateAmountBeforeTax.ts
> +  let result = {} as CalculateAmountBeforeTaxResultParams;
ご指摘ありがとうございます。
resultの定義を変更する方法で修正させてもらいました。
[```6b56b4```](https://github.com/Lorenzras/yumecoco-monorepo/pull/124/commits/6b56b4d9ead2c7b6506a997168485ed833f67e48)にてご確認をお願いいたします。

2023-02-17 01:30 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/BillingTotalBody.tsx
>        if (isForPayment !== true) return acc;
ご指摘ありがとうございます。
[```6b56b4```](https://github.com/Lorenzras/yumecoco-monorepo/pull/124/commits/6b56b4d9ead2c7b6506a997168485ed833f67e48)にて修正しました。

2023-02-17 01:32 UTC, RPA02coco commented
ご確認ありがとうございます。
[```0d66ec```](https://github.com/Lorenzras/yumecoco-monorepo/pull/124/commits/0d66ec21badddfed83088f0305c698aad2ab517c)にてフォルダ名を修正しました。
index.tsのincludeの設定修正は、[```6b56b4```](https://github.com/Lorenzras/yumecoco-monorepo/pull/124/commits/6b56b4d9ead2c7b6506a997168485ed833f67e48)で対応しています。

2023-02-17 03:22 UTC, Lorenzras approved these changes
確認しました。

2023-02-17 03:22 UTC, merged