請求入力：請求合計欄に消費税額の表示を追加する
Lorenzras/yumecoco-monorepo pull request #131
Opened 2023-02-15 05:06 UTC by RPA02coco

**変更**
---

 - 請求合計欄に消費税額の表示を追加します
 - 合わせて、表示内容を調整します

**変更理由**
---

 - 請求書の表示仕様に合わせる
 - 他、[カード](https://trello.com/c/wkACSAMb/261-t156-%E8%AB%8B%E6%B1%82%E5%90%88%E8%A8%88%E6%AC%84%E3%81%AE%E8%A1%A8%E7%A4%BA%E8%AA%BF%E6%95%B4)参照

2023-02-17 06:37 UTC, Lorenzras requested changes
確認しました。挙動に問題ないと思います。

2023-02-17 06:37 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/BillingTotalBody.tsx
> +  }
特にFormikではレンダリングが多いので、計算の回数をuseMemoで抑えた方がいいと思います。

2023-02-20 02:22 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/BillingTotal.tsx
>    interface billingTotalTbl {
ご指摘ありがとうございます。
[```5383343```](https://github.com/Lorenzras/yumecoco-monorepo/pull/131/commits/5383343c8de0952b1df51cb8d58ec388d3bccc24)にて、修正しました。

2023-02-20 02:22 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/BillingTotal.tsx
>    }] as billingTotalTbl[];
ご指摘ありがとうございます。
[```5383343```](https://github.com/Lorenzras/yumecoco-monorepo/pull/131/commits/5383343c8de0952b1df51cb8d58ec388d3bccc24)にて、修正しました。

2023-02-20 02:35 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/BillingTotalBody.tsx
> +  }
ご指摘ありがとうございます。
[```87a05e5```](https://github.com/Lorenzras/yumecoco-monorepo/pull/131/commits/87a05e5ce6506f4dfb1a7836cdfdeaf583d5e7a1)にて修正しました。

2023-02-20 05:00 UTC, Lorenzras approved these changes
確認しました。
問題ないと思います。

2023-02-20 05:08 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/BillingTotal.tsx
> +  }];
承知しました。
ご指摘ありがとうございます。

2023-02-20 05:08 UTC, merged