請求入力：請求する見積りのIDをURLに追加する
Lorenzras/yumecoco-monorepo pull request #132
Opened 2023-02-17 01:43 UTC by RPA02coco

**変更**
---

 - 請求入力画面に置いて、「請求に使用する」にチェックを入れた際、チェックした見積もりのIDをURLに追加します。
 - 同様に、チェックを外した際には見積もりのIDをURLから削除します。

**変更理由**
---

 - https://trello.com/c/qJ4VmnR9

2023-02-17 05:39 UTC, Lorenzras requested changes
確認しました。URLのestimateIDの配列ですが、`", "` -> `","` 、可能でしょうか。

URLに配列の指定の仕方は色々ありますが、カスタム以外、以下のどちらかでいいと思います。
https://www.npmjs.com/package/query-string

2023-02-17 05:39 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/EstimatesTableBody.tsx
> +  const handleChange = (_: any, val: boolean | null) => {
```suggestion
  const handleChange = (_: ChangeEvent<HTMLInputElement>, checked: boolean) => {
```
ここは不要な引数ですが、出来るだけanyを避けたほうがよさそうです。

もう一つのやり方は以下の通りです。

```
const handleChange = (checked: boolean) => { ..// 処理 }

...
onChange = {(_, checked) => handleChange(checked) }
...
```

2023-02-17 05:39 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/EstimatesTableBody.tsx
> +    let newEstimateId = (estimateIdFromURL)?.split(', ');
変更不要。以下も可能です。

````
 ...
 const handleChange = (checked: boolean) => { 
   const estimateIdArray = projEstimateId?.split(', ') ?? [];
   const newEstimateIdArray = checked
      ? [...estimateIdArray, estimateId]
      : estimateIdArray.filter((id) => id !== estimateId);
 } 
...

 // 省略
```

2023-02-17 05:39 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/EstimatesTableBody.tsx
> +  };
projInvoiceIdFromURLは存在チェックしなくても、generateParams　は一つで行けるかもしれません。

2023-02-17 06:03 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/EstimatesTableBody.tsx
> +  const handleChange = (_: any, val: boolean | null) => {
ご指摘ありがとうございます。
コメントで提示して頂いた方が分かりやすく見えたため、そちらで修正させてもらいました。
[```a49433d```](https://github.com/Lorenzras/yumecoco-monorepo/pull/132/commits/a49433d5f5c75e188ca2316d64153e13c661ee7e)にて対応済みです

2023-02-17 06:04 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/EstimatesTableBody.tsx
> +    let newEstimateId = (estimateIdFromURL)?.split(', ');
ご指摘ありがとうございます。
変更不要とのことでしたが、処理が分かりやすくスマートだと思うので、上記内容で修正させてもらいました。
[```a49433d```](https://github.com/Lorenzras/yumecoco-monorepo/pull/132/commits/a49433d5f5c75e188ca2316d64153e13c661ee7e)にて対応済みです。

2023-02-20 02:03 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/EstimatesTableBody.tsx
> +  };
確認しました。
projInvoiceIdFromURLの存在チェックを外し、処理をまとめました。
その過程で、invoiceIdがある請求の変更を行う際にestimateIdが拾えなくなる現象に気付きましたので、合わせて修正させてもらっています。

修正は[```aac70c0```](https://github.com/Lorenzras/yumecoco-monorepo/pull/132/commits/aac70c043d1703cb71e0a1ff7f4ee38fd2fd316b)にて織り込んでいます。

2023-02-20 02:04 UTC, RPA02coco commented
> 確認しました。URLのestimateIDの配列ですが、", " -> "," 、可能でしょうか。

本件についても[```aac70c0```](https://github.com/Lorenzras/yumecoco-monorepo/pull/132/commits/aac70c043d1703cb71e0a1ff7f4ee38fd2fd316b)にて対応しました。

2023-02-20 04:37 UTC, Lorenzras submitted a review, later dismissed
確認しました。コメント対応したら、マージOKです。:rocket:

2023-02-20 04:37 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/api/convertInvoiceToForm.ts
> +      isForPayment: ((tgtBillingAmount === '0') && !isForPaymentFromURL) ? false : true,
```suggestion
      isForPayment: tgtBillingAmount !== '0' || isForPaymentFromURL
```

可読性と処理速度 🆙

2023-02-20 04:37 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/hooks/useResolveParams.ts
> +          const newIsForPayment = estimateIdFromURL?.split(',').some((item) => item === data.estimateId) ?? false;
```suggestion
          
          const newIsForPayment = (estimateIdFromURL || '').split(',').includes(data.estimateId);
          // uuidなのでこれも可能ですが、それ以外、上の方が安全。const newIsForPayment = (estimateIdFromURL || '').includes(data.estimateId);
```

2023-02-20 04:59 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/api/convertInvoiceToForm.ts
> +      isForPayment: ((tgtBillingAmount === '0') && !isForPaymentFromURL) ? false : true,
確認ありがとうございます。
[```31b61f9```](https://github.com/Lorenzras/yumecoco-monorepo/pull/132/commits/31b61f9a34df33882c2f8ba9246a0904c6bf6cfe)にて修正しました。
動作に影響ないことも確認済みです。

2023-02-20 04:59 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/hooks/useResolveParams.ts
> +          const newIsForPayment = estimateIdFromURL?.split(',').some((item) => item === data.estimateId) ?? false;
確認ありがとうございます。
[```31b61f9```](https://github.com/Lorenzras/yumecoco-monorepo/pull/132/commits/31b61f9a34df33882c2f8ba9246a0904c6bf6cfe)にて修正しました。
動作に影響ないことも確認済みです。

2023-02-20 05:02 UTC, Lorenzras approved these changes
確認しました。

2023-02-20 05:02 UTC, merged