請求入力：契約金額と符号の異なる請求金額は入力不可にする
Lorenzras/yumecoco-monorepo pull request #133
Opened 2023-02-17 05:09 UTC by RPA02coco

**変更**
---

 - 契約書が0円以上の場合、請求金額にも0円以上を入力する
 - 同じく、契約書が0円未満の場合は、請求金額は0円未満を入力する

**変更理由**
---

 - 現状、返金する契約に対して請求を掛けられてしまう。逆も然り。
 - 望ましい形ではないため、バリデーション修正にて対応する
 - https://trello.com/c/wImjgI6D

2023-02-20 05:30 UTC, Lorenzras requested changes
確認しました。挙動に問題ないと思います。

2023-02-20 05:30 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/FormInvoice.tsx
>    });
変更不要

```
  const exceeded =  estimates.some(({ contractAmount, billedAmount, billingAmount, isForPayment }) => {
    const totalBilledAmount = +billedAmount + +billingAmount;
    const isUnderContractAmount = (+contractAmount > 0) && (totalBilledAmount > +contractAmount);
    const isOverContractAmount = (+contractAmount <= 0) && (totalBilledAmount < +contractAmount);

    return isForPayment && (isUnderContractAmount || isOverContractAmount);
});
```

可読性 🆙

2023-02-20 05:30 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/formValidation.ts
> +const billingAmountValidation = function (this: any) {
```suggestion
const billingAmountValidation = function (this: { parent: TypeOfForm['estimates'][number] }) {
```

変更に簡単に対応出来るように、`any` は出来るだけ使わないほうがいいと言われています。

2023-02-20 05:53 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/FormInvoice.tsx
>    });
ご指摘ありがとうございます。
変更不要とのことでしたが、こちらの方が分かりやすい為、修正させていただきました。

[```b44090c```](https://github.com/Lorenzras/yumecoco-monorepo/pull/133/commits/b44090ca94b61ecc4366280904fdcda89ffece54)にて対応しています。

2023-02-20 05:53 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/formValidation.ts
> +const billingAmountValidation = function (this: any) {
ご指摘ありがとうございます。
[```b44090c```](https://github.com/Lorenzras/yumecoco-monorepo/pull/133/commits/b44090ca94b61ecc4366280904fdcda89ffece54)にて修正しました。

2023-02-20 05:55 UTC, RPA02coco commented
口頭でもお伝えしましたが、超過フラグの処理でバグを入れてしまったため修正しています。
基本的に処理を巻き戻しているのみです。
[```5458ec9```](https://github.com/Lorenzras/yumecoco-monorepo/pull/133/commits/5458ec90bf745b2e5d9bf8222dff1a49804f310e)にて対応しましたので、お手数ですがご確認をお願いいたします。

2023-02-21 01:38 UTC, Lorenzras requested changes
「exceeded」という語は、親子のコンポーネントにも存在していますが、変数の役割に合わせて使用することもできます。そのため、それぞれの変数に合った名前を付けることをおすすめします。例えば、「totalAmountExceeded」と「rowAmountExceeded」などはいかがでしょうか。これにより、コードの可読性が向上し、わかりやすいコードとなると思います。

2023-02-21 04:08 UTC, RPA02coco commented
ご指摘ありがとうございます。
変数名を提案して頂いた内容で修正しました。
また、合わせて昨日口頭でお聞きしたwarningアイコンカラーも修正しています。

ご確認をお願いいたします。

2023-02-21 05:07 UTC, Lorenzras approved these changes
確認しました。コードと挙動に問題ないと思います。

2023-02-21 05:07 UTC, merged