T258-案件をANDPADへ保存処理
Lorenzras/yumecoco-monorepo pull request #136
Opened 2023-02-20 07:35 UTC by Lorenzras

todo

2023-02-20 07:36 UTC, Lorenzras commented
![](https://github.trello.services/images/mini-trello-icon.png) [ANDPAD-API：保存の実装](https://trello.com/c/ZqRzLidY/258-andpad-api%EF%BC%9A%E4%BF%9D%E5%AD%98%E3%81%AE%E5%AE%9F%E8%A3%85)

2023-02-21 03:29 UTC, RPA02coco requested changes
確認しました。(可能な限りにはなってしまっています。。。)
コメント残しましたので、ご確認をお願いいたします。

2023-02-21 03:29 UTC, RPA02coco commented on packages/kokoas-client/src/lib/bestStringMatch.test.ts
> +  it('should return matching 工事種別', async () => {
このテストの実行時に、エラーになってしまいました。
※　[KintoneRestAPIError: [520] [CB_AU01] ログインしてください。]
kintone, andpadにはログインした状態でした。

確認をお願いいたします。

2023-02-21 03:29 UTC, RPA02coco commented on packages/kokoas-client/src/lib/bestStringMatch.test.ts
> +  it('should return matching 店舗名', async () => {
''should return matching 工事種別''のテストと同様にエラーになってしまいました。
ご確認をお願いいたします。

2023-02-21 03:49 UTC, Lorenzras commented on packages/kokoas-client/src/lib/bestStringMatch.test.ts
> +  it('should return matching 工事種別', async () => {
確認ありがとうございます。0494a93a 修正を入れました。 

puppeteerによるE2Eテストが機能しなくなりますが、[cypress ](https://www.cypress.io/) に移行する方針なので、そのままにしておきます。

2023-02-21 03:51 UTC, Lorenzras commented on packages/kokoas-client/src/lib/bestStringMatch.test.ts
> +  it('should return matching 店舗名', async () => {
ありがとうございます。上記と同様対応でした。

2023-02-21 04:17 UTC, RPA02coco approved these changes
修正を確認しました。
ご対応ありがとうございます。

2023-02-21 04:48 UTC, merged