請求入力：破棄した請求を請求済み金額から除外する
Lorenzras/yumecoco-monorepo pull request #146
Opened 2023-02-24 02:04 UTC by RPA02coco

**関連**
---

 - #143 より派生
 - 先に上記PRの確認をお願いします

**変更**
---

 - 請求済み金額の表示から、破棄した請求書の分の金額を除外します

**変更理由**
---

 - 請求書のステータスvoided(破棄)に対応するため
 - https://trello.com/c/iA8l57hS

2023-02-25 05:02 UTC, Lorenzras requested changes
確認しました。

useInvoiceTotalByCustGroupIdという名前と、その関数が行うこととの間にズレがあるように感じられます。useInvoicesSummaryByCustGroupIdという名前の方が、より的確な説明をしているように思えます。

2023-02-25 05:11 UTC, Lorenzras requested changes
確認しました。

2023-02-25 05:11 UTC, Lorenzras commented on packages/kokoas-client/src/hooksQuery/useInvoiceTotalByCustGroupId.ts
> +  createdAmount: number,
変数名のリファクタリング提案として、EstimateList インターフェースの名称を EstimateSummary に変更することはいかがでしょうか。名称の変更によって、単一の見積もりに関する情報の概要を提供することが目的であることをより明確に表現できると思われます。

2023-02-27 02:07 UTC, RPA02coco commented on packages/kokoas-client/src/hooksQuery/useInvoiceTotalByCustGroupId.ts
> +  createdAmount: number,
提案して頂いた内容がとても分かりやすく、良いと思います！
ご指摘の内容で、インターフェイス名を修正しました。
[05904aa](https://github.com/Lorenzras/yumecoco-monorepo/pull/146/commits/05904aaa26b04876d065285668289a506c726b04)にて、ご確認をお願いいたします。

2023-02-27 02:09 UTC, RPA02coco commented
>useInvoiceTotalByCustGroupIdという名前と、その関数が行うこととの間にズレがあるように感じられます。useInvoicesSummaryByCustGroupIdという名前の方が、より的確な説明をしているように思えます。

ご指摘の内容のほうが分かりやすいと思いますので、修正しました。
[05904aa](https://github.com/Lorenzras/yumecoco-monorepo/pull/146/commits/05904aaa26b04876d065285668289a506c726b04)にて、対応しました。
ご確認をお願いいたします。

2023-02-28 00:16 UTC, Lorenzras requested changes
確認しました！コメントの対応ありがとうございます。後一件です。

2023-02-28 00:16 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/hooks/useResolveParams.ts
> +  const { data: datInvoicesTotal } = useInvoicesSummaryByCustGroupId(newCustGroupId || '');
```suggestion
  const { data: datInvoicesSummary } = useInvoicesSummaryByCustGroupId(newCustGroupId || '');
```

2023-02-28 01:08 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/hooks/useResolveParams.ts
> +  const { data: datInvoicesTotal } = useInvoicesSummaryByCustGroupId(newCustGroupId || '');
ご指摘ありがとうございます。
```convertInvoiceToForm```にも同様の修正漏れがあったため、合わせて修正しました。
[199c83c](https://github.com/Lorenzras/yumecoco-monorepo/pull/146/commits/199c83cab94d36a231203c5dd2295eeb39d53caa)にて、ご確認をお願いいたします。

2023-02-28 06:04 UTC, Lorenzras commented
test

2023-02-28 06:11 UTC, Lorenzras approved these changes
！確認しました！

2023-02-28 06:12 UTC, merged