請求入力：作成済み金額を契約一覧の項目に追加する
Lorenzras/yumecoco-monorepo pull request #147
Opened 2023-02-24 02:37 UTC by RPA02coco

**関連**
---

 - #146 より派生
 - 先に上記PRの確認をお願いいたします

**変更**
---

 - 契約一覧表に、「作成済み金額」の表示を追加します

**変更理由**
---

 - 請求書のステータス追加に伴う要件変更への対応
 - https://trello.com/c/ORN1hpG7

2023-02-25 06:12 UTC, Lorenzras requested changes
確認しました。コメントの対応をお願いします。

2023-02-25 06:12 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/hooks/useResolveParams.ts
> +          const tgtCreatedAmount = datInvoicesTotal?.find(({ dataId }) => dataId === data.dataId)?.createdAmount ?? 0;
```suggestion
          const targetInvoice = datInvoicesTotal?.find(invoice => invoice.dataId === data.dataId);
          const {
            billedAmount = 0,
            createdAmount = 0,
          } = targetInvoice || {};
```

datInvoicesTotalにおけるfindの繰り返し利用を避け、配列から目的の値を直接取得する方法を使用することができます。

2023-02-27 02:23 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/api/convertInvoiceToForm.ts
> +    const tgtAmount = datInvoicesTotal?.find(({ dataId: dataIdOfInvoice }) => {
ご提案ありがとうございます。
上記変数名で修正しました。
[0b5bb97](https://github.com/Lorenzras/yumecoco-monorepo/pull/147/commits/0b5bb97efdd8ccbceaf92b91ab69bb1749313896)にて、ご確認をお願いいたします。

2023-02-27 02:24 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/hooks/useResolveParams.ts
> +          const tgtCreatedAmount = datInvoicesTotal?.find(({ dataId }) => dataId === data.dataId)?.createdAmount ?? 0;
ご指摘ありがとうございます。
上記内容で修正しました。
[0b5bb97](https://github.com/Lorenzras/yumecoco-monorepo/pull/147/commits/0b5bb97efdd8ccbceaf92b91ab69bb1749313896)にて、ご確認をお願いいたします。

2023-02-27 02:27 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/CreatedAmountToolTip.tsx
> +import InfoIcon from '@mui/icons-material/Info';
ご提案ありがとうございます。
確認してみましたが、こちらの方が主張が抑えめでページに馴染むので、変更させてもらいました。
[a3d0c7f](https://github.com/Lorenzras/yumecoco-monorepo/pull/147/commits/a3d0c7fae44bd8be77987d5030717c00ae268e71)にて、ご確認をお願いいたします。

2023-02-28 00:28 UTC, Lorenzras approved these changes
確認しました。問題ないと思います。

2023-02-28 01:29 UTC, merged