請求入力：既存の請求を選択できる機能を実装する
Lorenzras/yumecoco-monorepo pull request #148
Opened 2023-02-24 05:01 UTC by RPA02coco

**変更**
---

 - 既存の請求書を選択するボタンを設置する

**変更理由**
---

 - https://trello.com/c/06WNPc0y

2023-02-24 05:15 UTC, RPA02coco commented
@Lorenzras 
```InvoicesDialogContentProps ```において、```useInvoicesByCustGroupId```の戻り値の型が取得できず、その部分だけ仮実装させて頂いています。
すみませんが、また別途ご教授お願いします。

2023-02-25 06:43 UTC, Lorenzras commented
> @Lorenzras `InvoicesDialogContentProps `において、`useInvoicesByCustGroupId`の戻り値の型が取得できず、その部分だけ仮実装させて頂いています。 すみませんが、また別途ご教授お願いします。

了解です！関連のコードを確認します。

2023-02-26 06:20 UTC, Lorenzras requested changes
確認させていただきました。見積画面と共通する部分があるようですが、安定したら再利用できるコンポーネントにすることができると思います。そのため、変更等は一箇所で対応できるようになると思います。

そして、選択肢に関する件なんですけど、金額は右揃えにすると比較しやすいそうです。でも、UX/UIデザインは状況によって異なるので、自信がないです。多分、高橋さんに確認したほうが確実です。

2023-02-27 03:02 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/ConfirmationDialogInvoice.tsx
> +  onClose: (value?: string) => void;
MUIの参考コードを引用したままになっていました。すみません。
使用していないため、削除しました。
[8b305bf](https://github.com/Lorenzras/yumecoco-monorepo/pull/148/commits/8b305bf9327c31f362891a3e6d9f8154d5f156e6)にて修正しましたので、ご確認をお願いいたします。

2023-02-27 03:02 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/InvoicesDialogContent.tsx
> +  const { data } = useInvoicesByCustGroupId(custGroupId);
ありがとうございます！！
なぜ```unknown```になるのかが分からず四苦八苦していたため、とても助かりました。
ジェネリック型の理解ができていなかったため、合わせてwebで確認しました。

説明の確認と試行の結果、今回は 2. で提案して頂いた方法がスマートなのかな、と感じましたので、そちらで修正させてもらっています。

[8b305bf](https://github.com/Lorenzras/yumecoco-monorepo/pull/148/commits/8b305bf9327c31f362891a3e6d9f8154d5f156e6)にて修正しましたので、ご確認をお願いいたします。

2023-02-27 03:03 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/InvoicesDialogContent.tsx
> +      {!(actualOptions.length) &&
[8b305bf](https://github.com/Lorenzras/yumecoco-monorepo/pull/148/commits/8b305bf9327c31f362891a3e6d9f8154d5f156e6)にて修正しましたので、ご確認をお願いいたします。

2023-02-27 04:35 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/ListItemInvoices.tsx
> +const ListContent = ({
提案の内容の方が内容に合うと思いますので、修正しました。
[a6105be](https://github.com/Lorenzras/yumecoco-monorepo/pull/148/commits/a6105be9d718c1e16d9832c0f2c49375278fc160)にて、ご確認をお願いいたします。

2023-02-27 04:36 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/ListItemInvoices.tsx
> +  invoiceRecords: IInvoices
承知しました。
[a6105be](https://github.com/Lorenzras/yumecoco-monorepo/pull/148/commits/a6105be9d718c1e16d9832c0f2c49375278fc160)にて修正しました。
ご確認をお願いいたします。

2023-02-27 04:36 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/ListItemInvoices.tsx
> +  explanation: string
labelで修正しました。
[a6105be](https://github.com/Lorenzras/yumecoco-monorepo/pull/148/commits/a6105be9d718c1e16d9832c0f2c49375278fc160)にて、ご確認をお願いいたします。

2023-02-27 04:37 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/ListItemInvoices.tsx
> +  Icon: OverridableComponent<SvgIconTypeMap<Record<string, unknown>, 'svg'>>,
ご指摘・ご提案ありがとうございます！
上記を参考に、[a6105be](https://github.com/Lorenzras/yumecoco-monorepo/pull/148/commits/a6105be9d718c1e16d9832c0f2c49375278fc160)にて修正しました。
ご確認をお願いいたします。

2023-02-27 04:38 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/ListItemInvoices.tsx
> +      <ListContent Icon={NumbersIcon} explanation={String(id.value)} />
すみません、単純に私のミスです。
ListItemEstimateから流用しており、その時から不要な処理になっています。
[a6105be](https://github.com/Lorenzras/yumecoco-monorepo/pull/148/commits/a6105be9d718c1e16d9832c0f2c49375278fc160)にて修正しました。
ご確認をお願いいたします。

2023-02-27 04:39 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/InvoicesDialogContent.tsx
> +  }).map<OptionNode>((rec) => {
参考リンクもありがとうございます。勉強させてもらいました。
[a6105be](https://github.com/Lorenzras/yumecoco-monorepo/pull/148/commits/a6105be9d718c1e16d9832c0f2c49375278fc160)にて修正しましたので、ご確認をお願いいたします。

2023-02-27 04:51 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/SelectInvoices.tsx
> +        name='invoiceId'
本コンポーネントですがestimateから流用してしまっています。
上記の```name```ですが、ラジオボタンMUI```RadioGroup```の```name```,```aria-label```等の設定に使用しており、特に制限はつけていません。
確認しましたが、nameを持たせる必要がないのかと思い、一旦削除させてもらいました。
コンポーネントを共有化する際に、また検討させていただきます。

[95b7519](https://github.com/Lorenzras/yumecoco-monorepo/pull/148/commits/95b7519675d2c834d327b474b5f2cf24b9c0968f)にて修正していますので、ご確認をお願いいたします。

2023-02-27 04:54 UTC, RPA02coco commented
ご確認ありがとうございます。
今回ご指摘頂いた分も反映しているので、請求入力ページである程度固めたものでコンポーネントの共有化をしようと思います。

なお、金額の表示については先ほど仕様を確認したため、別PRにて対応させていただきます。

2023-02-28 00:40 UTC, Lorenzras approved these changes
確認しました！コメントを残しましたが。変更不要です。

2023-02-28 00:40 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/InvoicesDialogContent.tsx
> +  const { data } = useInvoicesByCustGroupId<GetInvoicesByCustGroupId>(custGroupId);
変更不要。
```suggestion
  const { data } = useInvoicesByCustGroupId(custGroupId);
```

デフォルトのuseInvoicesByCustGroupIdのジェネリックタイプから、既にタイプが推論されているため、ここで明示的に定義しなくてもいいと思います。

2023-02-28 01:14 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/InvoicesDialogContent.tsx
> +  const { data } = useInvoicesByCustGroupId<GetInvoicesByCustGroupId>(custGroupId);
承知しました。
別途、修正できるタイミングで対応します。

2023-02-28 01:14 UTC, merged