請求入力：ダイアログ内の金額表示を右揃えにする
Lorenzras/yumecoco-monorepo pull request #154
Opened 2023-02-28 02:00 UTC by RPA02coco

**変更**
---

 - 「請求書を選択」の画面において、金額を右揃えで表示する

**変更理由**
---

 - 要件の明確化によります
 - https://trello.com/c/9lT8hkWX

2023-03-01 07:49 UTC, Lorenzras requested changes
めっちゃいい感じになりました！

UXの面ではMaterial UI によると
- ボーダーがるので、ボタン間にスペースを開けた方がよさそうです。
- ボタン内のパディングは最小4px。MUIだと p={1}

https://m2.material.io/design/layout/spacing-methods.html#spacing

2023-03-01 07:49 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/InvoicesDialogContent.tsx
> +      tipComponent: infoToolTip,
コンポーネント内にコンポネントを変数に格納ものは少ないならいいと思いますが、多くなると、分解したほういいと思います。

理由：

1. 処理速度。一回目は map で　actualOptions　を定義して、return で、また mapで回す。コンポーネントはオブジェクトなので、より重くなります。
2. 可読性。コンポーネント内でのレンダリング処理は、コンポーネントの中で行われるため、コンポーネントの中身が複雑になってしまい、可読性が低下してしまうということが挙げられます。一方、戻り値でレンダリング処理を行う場合は、コンポーネントの中身がシンプルになり、コードの理解や修正が容易になります。
3. 汎用性。コンポーネント内でデータだけを扱い、レンダリング処理を戻り値で行う場合、同じデータに対して、複数のコンポーネントを使い回すことができるからです。つまり、同じデータを扱う場面が増えたとしても、そのデータに対するレンダリング処理は変わらず、再利用が容易になります。

以上の理由から、データのみでレンダリング処理は戻り値にすることが望ましい場合があると考えられます。

```suggestion
      ...
      record: rec,
      }
      
      ...
      
      return (
      ...
        <ListItemInvoices invoiceRecord={rec} />
      ...
      )
```

参考：https://github.com/alan2207/bulletproof-react/blob/master/docs/components-and-styling.md

2023-03-01 07:49 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/InvoicesDialogContent.tsx
> +                key={option.key}
```suggestion
           
```

2023-03-01 07:49 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/InvoicesDialogContent.tsx
> +              >
コンテナーのような存在で、Tooltip.tileの中身 も含めて、別のコンポーネントにした方いいかもしれません。


例えば (pseudocode)、
```
...
<ListInvoiceButtonWithToolTip key={uuid} estimateLists={estimateLists}>
  // <ListInvoiceButtonContent <ListItemInvoices invoiceRecord={record} />/>
</ListInvoiceButtonWithToolTip >
...
```

2023-03-01 07:49 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/ListItemInvoices.tsx
> +};
Typescript utilityに便利なRecordがあります。:heart: 

https://www.typescriptlang.org/docs/handbook/utility-types.html

```suggestion

const invoiceStatusJa: Record<InvStatusJa, string> = {
  'created': '作成済',
  'sent': '発行済',
  'voided': '破棄',
  'completed': '完了',
  '': '',
};
```

2023-03-02 00:49 UTC, Lorenzras commented
私は認識が合わないところがあると思いますので、コンポーネントの構成について、確認したいことがあります。

2023-03-03 04:09 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/ListItemInvoices.tsx
>  export const ListItemInvoices = ({
度々すみません。
[f75fc1c](https://github.com/Lorenzras/yumecoco-monorepo/pull/154/commits/f75fc1c90687dff8ee860c6e2cf6c69c469671b9)にて修正しました。
ご確認をお願いいたします。

2023-03-03 04:09 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/ListItemInvoices.tsx
> +  });
ご指摘ありがとうございます。
上記内容で、関連する箇所も含めて修正しました。
[f75fc1c](https://github.com/Lorenzras/yumecoco-monorepo/pull/154/commits/f75fc1c90687dff8ee860c6e2cf6c69c469671b9)にて、ご確認をお願いいたします。

2023-03-03 04:10 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/InvoicesDialogContent.tsx
> +    const infoToolTip: ReactNode = (
ご指摘ありがとうございます。
削除しても問題ないことを確認しました。
[f75fc1c](https://github.com/Lorenzras/yumecoco-monorepo/pull/154/commits/f75fc1c90687dff8ee860c6e2cf6c69c469671b9)にて修正済みです。

2023-03-03 04:10 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/InvoicesDialogContent.tsx
> +      </Box>);
すみません、単純なミスです。
ソースコードのコピペにより残ってしました。
[f75fc1c](https://github.com/Lorenzras/yumecoco-monorepo/pull/154/commits/f75fc1c90687dff8ee860c6e2cf6c69c469671b9)にて修正しました。

2023-03-03 04:10 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/InvoicesDialogContent.tsx
> +  };
承知しました。
コンポーネント外部へ定義箇所を変更しました。
[f75fc1c](https://github.com/Lorenzras/yumecoco-monorepo/pull/154/commits/f75fc1c90687dff8ee860c6e2cf6c69c469671b9)にて修正しました。

2023-03-03 04:11 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/InvoicesDialogContent.tsx
> +                key={option.key}
keyの記載削除しました。
[f75fc1c](https://github.com/Lorenzras/yumecoco-monorepo/pull/154/commits/f75fc1c90687dff8ee860c6e2cf6c69c469671b9)にて修正しましたので、ご確認をお願いいたします。

2023-03-03 04:12 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/selectInvoices/ListItemInvoices.tsx
> +};
参考URLありがとうございます。
[f75fc1c](https://github.com/Lorenzras/yumecoco-monorepo/pull/154/commits/f75fc1c90687dff8ee860c6e2cf6c69c469671b9)にて、上記内容で修正しました。
ご確認をお願いいたします。

2023-03-03 04:24 UTC, RPA02coco commented
ボタン間のスペースを[324fdd0](https://github.com/Lorenzras/yumecoco-monorepo/pull/154/commits/324fdd0e63d1464f1f4c4b92979154429c0c2c64)にて追加しました。
ご確認をお願いいたします。

2023-03-03 04:26 UTC, Lorenzras approved these changes
確認しました！
問題無いと思います。

2023-03-03 04:50 UTC, merged