請求入力：発行ボタンを押したときPDFを表示する
Lorenzras/yumecoco-monorepo pull request #157
Opened 2023-03-01 05:16 UTC by RPA02coco

**変更**
--- 

 - 請求書発行・再発行ボタンを押したとき、PDFを表示する処理を実装する

**変更理由**
---

 - 請求書発行処理を分割して実装します
 - https://trello.com/c/iA8l57hS

2023-03-09 06:07 UTC, RPA02coco commented on packages/kokoas-server/src/route/kokoas.ts
> +  reqGetInvoiceReport,
コード修正して対応しました。

2023-03-14 00:53 UTC, Lorenzras requested changes
確認しました。コードには問題がなさそうです。ただ、この関数が期待通りに動作するかどうかを確認するために、単体テストとE2Eテストを追加することをお勧めします。

E2Eテストについては、少なくとも「発行ボタンを押したとき、PDFが表示されるかどうか」をテストする必要があります。お手数をおかけしますが、ご確認のほどよろしくお願いします。

2023-03-14 00:53 UTC, Lorenzras commented on packages/kokoas-server/src/handleRequest/putInvoiceReport/generateInvoicePdf.ts
> +  /* test用のコード　ここから */
PDF生成に関する単体テストがあると、開発効率が高まると考えています。

2023-03-14 00:53 UTC, Lorenzras commented on packages/kokoas-server/src/handleRequest/putInvoiceReport/parseInvoiceDat.test.ts
> +  it('should validate file', async () => {
テストしている関数を見る限り、以下はいかがでしょうか。

```suggestion
  it('returns a parsed invoice record object', async () => {
```

2023-03-15 01:27 UTC, RPA02coco commented on packages/kokoas-server/src/handleRequest/putInvoiceReport/parseInvoiceDat.test.ts
> +  it('should validate file', async () => {
ご指摘ありがとうございます。
英語がまだまだ難しいので、とても助かりました。
[0717b84](https://github.com/Lorenzras/yumecoco-monorepo/pull/157/commits/0717b84476b6ce63d556d6570e916b4f7c771b66)にて修正しました。
ご確認をお願いいたします。

2023-03-15 01:34 UTC, RPA02coco commented on packages/kokoas-server/src/handleRequest/putInvoiceReport/generateInvoicePdf.ts
> +  /* test用のコード　ここから */
ご指摘ありがとうございます。
簡単な単体テストを[503cf1a](https://github.com/Lorenzras/yumecoco-monorepo/pull/157/commits/503cf1a2c91370539728bf290cb55d95cf3ee3b9)で追加しました。
ご確認をお願いします。

2023-03-15 01:46 UTC, RPA02coco commented
> E2Eテストについては、少なくとも「発行ボタンを押したとき、PDFが表示されるかどうか」をテストする必要があります。お手数をおかけしますが、ご確認のほどよろしくお願いします。

E2Eテストですが、別PR( #173 )にて対応します。

2023-03-16 00:31 UTC, Lorenzras requested changes
PRありがとうございます。変更を確認しました。よろしくお願いします。

2023-03-16 00:31 UTC, Lorenzras commented on packages/kokoas-server/src/handleRequest/putInvoiceReport/generateInvoicePdf.test.ts
> +
stringがtruthyかどうかチェックですね。ありがとうございます。

開発中、ココアスを開かなくても、PDF自体を確認するために、以下のテストはいかがですか。

```suggestion
  const savePath = path.join(__dirname, '../__TEST__', '請求書.pdf');
    const pdfBuffer = Buffer.from(result, 'base64');
    
    // __TEST__　フォルダー に 保存する
    fs.writeFileSync(savePath, pdfBuffer);

    // ファイルが存在するかどうかを確認する
    expect(fs.existsSync('path/to/file')).toBe(true);
```

2023-03-16 00:44 UTC, Lorenzras commented
> > E2Eテストについては、少なくとも「発行ボタンを押したとき、PDFが表示されるかどうか」をテストする必要があります。お手数をおかけしますが、ご確認のほどよろしくお願いします。
> 
> E2Eテストですが、別PR( #173 )にて対応します。

承知しました！網羅的でなくても大丈夫だそうです。

![image](https://user-images.githubusercontent.com/2501255/225480006-f55c5a64-e915-4c7f-aaf0-c07c8091e064.png)

2023-03-16 01:25 UTC, RPA02coco commented on packages/kokoas-server/src/handleRequest/putInvoiceReport/generateInvoicePdf.test.ts
> +
ご指摘ありがとうございます。
上記を参考に[0e1b526](https://github.com/Lorenzras/yumecoco-monorepo/pull/157/commits/0e1b526aa5fa02ac1720fb8541f184fa6622a79b)にて修正しました。

2023-03-16 01:27 UTC, RPA02coco commented
承知しました！
テスト項目について検討してみます。

2023-03-16 01:49 UTC, Lorenzras approved these changes
コードと当PRの動作を確認しました。

2023-03-16 01:52 UTC, merged