T276 契約一覧に契約のステータスを追加しました
Lorenzras/yumecoco-monorepo pull request #159
Opened 2023-03-04 05:21 UTC by Lorenzras

## 変更

- 契約一覧に契約のステータスを追加しました。

## 理由

https://trello.com/c/le7I9Fr2

2023-03-04 05:22 UTC, Lorenzras commented
![](https://github.trello.services/images/mini-trello-icon.png) [契約一覧に完了だけじゃなく、契約を進んでいるものも追加](https://trello.com/c/le7I9Fr2/276-%E5%A5%91%E7%B4%84%E4%B8%80%E8%A6%A7%E3%81%AB%E5%AE%8C%E4%BA%86%E3%81%A0%E3%81%91%E3%81%98%E3%82%83%E3%81%AA%E3%81%8F%E3%80%81%E5%A5%91%E7%B4%84%E3%82%92%E9%80%B2%E3%82%93%E3%81%A7%E3%81%84%E3%82%8B%E3%82%82%E3%81%AE%E3%82%82%E8%BF%BD%E5%8A%A0)

2023-03-06 02:56 UTC, RPA02coco requested changes
確認しました。
テストも問題なく動きました。
1点、コメント残させてもらいましたので、ご確認をお願いいたします。

2023-03-06 02:56 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projContractSearch/hooks/useFilteredContracts.ts
> +        if (!envStatus.value) return acc;
89行目で```!envStatus.value```の場合、86行目の変数は使用されないため、86行目と89行目の記載順を逆にしてはどうでしょうか。

別の意図があれば無視して頂いてOKです。

2023-03-06 03:04 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projContractSearch/hooks/useFilteredContracts.ts
> +        if (!envStatus.value) return acc;
指摘ありがとうございます。コメント通りに修正しました。 b99dbbbc  確認をお願いいたします。

2023-03-06 04:23 UTC, RPA02coco approved these changes
修正確認しました。
問題ないと思います。

2023-03-06 04:30 UTC, merged