T276 4 契約一覧-絞り込み
Lorenzras/yumecoco-monorepo pull request #163
Opened 2023-03-09 02:03 UTC by Lorenzras

## 変更

- 契約進歩でフィルター出来る機能。

## 理由

- https://trello.com/c/le7I9Fr2

2023-03-09 02:04 UTC, Lorenzras commented
![](https://github.trello.services/images/mini-trello-icon.png) [契約一覧に完了だけじゃなく、契約を進んでいるものも追加](https://trello.com/c/le7I9Fr2/276-%E5%A5%91%E7%B4%84%E4%B8%80%E8%A6%A7%E3%81%AB%E5%AE%8C%E4%BA%86%E3%81%A0%E3%81%91%E3%81%98%E3%82%83%E3%81%AA%E3%81%8F%E3%80%81%E5%A5%91%E7%B4%84%E3%82%92%E9%80%B2%E3%82%93%E3%81%A7%E3%81%84%E3%82%8B%E3%82%82%E3%81%AE%E3%82%82%E8%BF%BD%E5%8A%A0)

2023-03-10 02:02 UTC, RPA02coco requested changes
確認しました。動作問題ないと思います！
コメント残しましたので、ご確認をお願いいたします。

2023-03-10 02:41 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projContractSearch/helpers/getCurrentContractStep.ts
> +      return filtered[0];
そうですね。実際にはdocusignが送信されていない、「送信先詳細」のE2Eテスト用のものです。本番では普通はelseには入りませんが、テストで強制的に routeOrder を未完了の状態にして、そのまま残しています。

実際に未完了にするには、routingOrderと各送信先のstatusを編集する必要がありますが、routingOrderを変更するだけでも未完了の場合のテストができます。

テスト用のデータ生成スクリプトが完成すれば、これらのテスト用データは不要になります。

2023-03-10 02:44 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projContractSearch/hooks/useFilteredContracts.ts
> +
誤記です。 095798ac で 修正しました。指摘ありがとうございます。

2023-03-10 02:48 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projContractSearch/hooks/useFilteredContracts.ts
> +          contractStatus: envolopeStatus,
誤記です。 d92cff9c で 修正しました。指摘ありがとうございます。

gitHubのcopilotとやって、コード生成補助が私の最初の誤記を真似続けていましたｗ。

2023-03-10 02:52 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projContractSearch/helpers/getCurrentContractStep.ts
> +      return filtered[0];
了解です！
補足ありがとうございます。

2023-03-10 02:53 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projContractSearch/hooks/useFilteredContracts.ts
> +
[9b79ea5](https://github.com/Lorenzras/yumecoco-monorepo/pull/163/commits/9b79ea562a8130ca5f7ab1d33602d18828500e63)にて確認しました。

2023-03-10 02:55 UTC, RPA02coco approved these changes
確認しました

2023-03-10 02:56 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projContractSearch/hooks/useFilteredContracts.ts
> +
失礼しました。ありがとうございます！

2023-03-10 02:56 UTC, merged