T182-T234 見積xlsx出力機能
Lorenzras/yumecoco-monorepo pull request #172
Opened 2023-03-14 04:35 UTC by Lorenzras

## 変更

- 顧客用の見積を出力する

## 理由

- https://trello.com/c/EullNtax

2023-03-17 07:09 UTC, Lorenzras commented
![](https://github.trello.services/images/mini-trello-icon.png) [T182-見積xlsx出力機能 50](https://trello.com/c/EullNtax/234-t182-%E8%A6%8B%E7%A9%8Dxlsx%E5%87%BA%E5%8A%9B%E6%A9%9F%E8%83%BD-50)

2023-03-22 04:36 UTC, RPA02coco requested changes
確認しました。
コメント残しましたので、確認お願いします。

2023-03-22 04:36 UTC, RPA02coco commented on packages/kokoas-server/src/handleRequest/reqDownloadEstimateForCustomer/conversions/convertEstimateForCustomerById.ts
> +    ws.getCell(`G${rowIdx}`).value = totalAmountBeforeDiscount;
```suggestion
    rowIdx += 1;

    ws.getCell(`A${rowIdx}`).value = '《 合 計 》';
    ws.getCell(`G${rowIdx}`).value = totalAmountBeforeDiscount;
```

rowIdxの更新忘れにより、1項目分を上書きしてしまっているようです。

2023-03-22 04:36 UTC, RPA02coco commented on packages/kokoas-server/src/handleRequest/reqDownloadEstimateForCustomer/conversions/groupEstItems.test.ts
testの実行でエラーになってしまいます。
確認お願いします。

2023-03-22 04:36 UTC, RPA02coco commented on packages/kokoas-e2e/cypress/e2e/estimate/exporting.cy.ts
> +  it.only('EXCEL形式でエクスポート出来る', () => {
```.only```が付いたままですが、問題ないでしょうか？
確認をお願いします。

2023-03-22 04:36 UTC, RPA02coco commented on packages/kokoas-server/src/route/kokoas.ts
>    downloadEstimateAsAndpad,
念のため確認させてください。
```downloadEstimateAsAndpad```内でbodyの取得処理がない為、制限を削除している、という認識で合っているでしょうか？

2023-03-22 04:41 UTC, Lorenzras commented on packages/api-kintone/src/estimates/calculation/calculateEstimateSummary.test.ts
> +  it('正しい非割引非を返す', () => {
:bow: 59ab3def で対応しました。

2023-03-22 04:42 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projEstimate/formActions/exportMenu/ExportToAndpad.tsx
> +      message: 'この機能はベータ版です。不具合の報告につきましては、管理者までご連絡いただけますようお願いいたします。',
ありがとうございます！

2023-03-22 04:49 UTC, Lorenzras commented on packages/kokoas-server/src/handleRequest/reqDownloadEstimateForCustomer/conversions/convertEstimateForCustomerById.ts
> +    ws.getCell(`G${rowIdx}`).value = totalAmountBeforeDiscount;
気づきませんでした。ありがとうございます！ eab93b2f で対応しました。

2023-03-22 04:51 UTC, Lorenzras commented on packages/kokoas-e2e/cypress/e2e/estimate/exporting.cy.ts
> +  it.only('EXCEL形式でエクスポート出来る', () => {
問題ありですｗ。ありがとうございます。 bf088fde で対応しました。

2023-03-22 04:59 UTC, Lorenzras commented on packages/kokoas-server/src/route/kokoas.ts
>    downloadEstimateAsAndpad,
はい、そして、そもそもHTTPメソッドのGETは、一般的にボディーを持たないので、削除しました。

2023-03-22 05:09 UTC, Lorenzras commented on packages/kokoas-server/src/handleRequest/reqDownloadEstimateForCustomer/conversions/groupEstItems.test.ts
ありがとうございます！  bf088fde で対応しました。

2023-03-23 00:02 UTC, RPA02coco commented on packages/kokoas-server/src/route/kokoas.ts
>    downloadEstimateAsAndpad,
了解です！
このあたりはまだ理解が浅いので、情報助かりました。ありがとうございます！

2023-03-23 00:20 UTC, RPA02coco approved these changes
修正を確認しました。

2023-03-23 00:42 UTC, Lorenzras commented
> 修正を確認しました。

最終ページの"次へ" の削除と合計の追加を 06b9d8a3 にて対応しました。

2023-03-23 00:42 UTC, merged