T268-請求書発行のe2eテストを追加します
Lorenzras/yumecoco-monorepo pull request #173
Opened 2023-03-15 01:42 UTC by RPA02coco

**依存関係**
---

 - #157 より派生

**変更**
---

 - 請求書発行のe2eテストを追加します

**変更理由**
---

 - テスト未実装のため

2023-03-17 02:28 UTC, Lorenzras requested changes
`*=` と　first()　は不要なところがあります。大変申し訳ございませんが、こちらのコードにつきまして、少し気になる点がございます。もしよろしければご一緒に確認いただけますでしょうか。

`*=` と `first()` を使う必要があるかどうかを検討した結果、不要な部分があると判断いたしました。

そして、"請求書の動作確認：作成・更新・破棄" で以下のエラーがあります。

![image](https://user-images.githubusercontent.com/2501255/225793750-f9a5d259-86bd-4c28-8387-e0232d540197.png)

変更のほど、何卒よろしくお願い申し上げます。

2023-03-20 03:53 UTC, RPA02coco commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +    cy.get('input[name*="estimates[1].isForPayment"]').first()
承知しました！ご指摘ありがとうございます。
[e91c8e1](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/e91c8e17d3c1620103388f4242eda44c4986b545)にて修正しました。

2023-03-20 03:58 UTC, RPA02coco commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +      .as('table')
ご指摘ありがとうございます。
使用予定はない為、削除しました。
[a7b2da2](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/a7b2da2e16391e78655eb59b15e72293fb380180)にて、ご確認をお願いいたします。

2023-03-20 03:58 UTC, RPA02coco commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +    cy.contains('保存').click(); // 再発行ボタンをクリックする
すみません、誤記です。
[a7b2da2](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/a7b2da2e16391e78655eb59b15e72293fb380180)にて修正しました。

2023-03-20 06:50 UTC, Lorenzras commented
> #### ⚠️ GitGuardian has uncovered 4 secrets following the scan of your pull request.
> Please consider investigating the findings and remediating the incidents. Failure to do so may lead to compromising the associated services or software components.
> 
> 🔎 Detected hardcoded secrets in your pull request
> 🛠 Guidelines to remediate hardcoded secrets
> 🦉 [GitGuardian](https://dashboard.gitguardian.com/auth/login/?utm_medium=checkruns&utm_source=github&utm_campaign=cr1) detects secrets in your source code to help developers and security teams secure the modern development process. You are seeing this because you or someone else with access to this repository has authorized GitGuardian to scan your pull request.Our GitHub checks need improvements? [Share your feedbacks](https://050127dayho.typeform.com/to/KmeAPTMk)!

請求書のトークンを破棄させていただきました。
使うところがありましたら、新しいトークンの発行をお願いします。

2023-03-22 02:10 UTC, RPA02coco commented
>請求書のトークンを破棄させていただきました。
使うところがありましたら、新しいトークンの発行をお願いします。

対応ミスすみません。
上記、承知しました。
ご対応ありがとうございます。

2023-03-22 02:12 UTC, RPA02coco commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +    cy.contains('body', '契約金額と同じ符号(+, -)で入力してください')
承知しました。
[dd9c107](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/dd9c10729a3bba0c467478b75cfb0b8355206cc5)にて修正しましたので、ご確認をお願いいたします。

2023-03-22 02:13 UTC, RPA02coco commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +      .check();
[dd9c107](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/dd9c10729a3bba0c467478b75cfb0b8355206cc5)にて修正しました。

2023-03-22 02:15 UTC, RPA02coco commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +      .should('have.value', '2023/03/15');
情報ありがとうございます。
上記のaliasの説明を参考に、ファイルの内容を見直しました。
[dd9c107](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/dd9c10729a3bba0c467478b75cfb0b8355206cc5)にて対応しましたので、ご確認をお願いいたします。

2023-03-22 04:13 UTC, Lorenzras requested changes
確認しました。

テストの動作は問題ないと思います。

2023-03-22 04:13 UTC, Lorenzras commented on packages/kokoas-e2e/cypress.config.ts
> +      });
getAllInvoiceは重くなる見込みなで、直接的に必要なデータを取得する関数を作ったほうがよさそうです。

例：getInvoiceByEstDataId

2023-03-22 04:13 UTC, Lorenzras commented on packages/kokoas-e2e/cypress.config.ts
> +        async prepareInvoiceReissue(eissueInvoiceId: string) {
処理を見る限り、以下の関数名は適切だと思います。

```suggestion
        async setInvoiceStatusToSent(eissueInvoiceId: string) {
```

もし、利用目的を拡大するなら、setInvoiceStatus(invoiceId, status) でもいいと思います。

2023-03-22 04:13 UTC, Lorenzras commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +      .first()
```suggestion
      .first()
      .as('undecidedPaymentDateInput')
```

これで、他のところに、first()を指定しなくてもいけると思います。

2023-03-22 04:13 UTC, Lorenzras commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +    cy.url().should('not.include', 'custGroupId');
```suggestion
    cy.url()
    .should('include', 'invoiceId')
    .should('not.include', 'custGroupId');
```

2023-03-22 04:13 UTC, Lorenzras commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +      .type('-10000', { delay: 100 });
```suggestion
    cy.get('@billingAmountInput')
      .clear()
      .type('-10000', { delay: 100 });
```

2023-03-22 05:05 UTC, RPA02coco commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +  });
承知しました。
処理の修正方法に悩んで、2回分コミットしてしまいました。

[d1ac6ce](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/d1ac6ce7b96a9cb436e97dd2d3c30f4de836251b), [679a5d6](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/679a5d6816dbcfb5690853338ec98e83bd05e8c3)にて、ご確認をお願いいたします。

2023-03-22 05:09 UTC, RPA02coco commented on packages/kokoas-e2e/cypress.config.ts
> +        async prepareInvoiceReissue(eissueInvoiceId: string) {
ご指摘ありがとうございます。
とりあえずは実装内容は変更しませんでした。
[02dc948](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/02dc948207553e1435c64097aa07fc6b0f25d47e)にて修正しました。

2023-03-22 05:13 UTC, RPA02coco commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +      .first()
ご指摘ありがとうございます。
[a1793f3](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/a1793f37f26a15c1b6681586927d3ae9580db1b1)にて修正しました。

2023-03-22 05:15 UTC, RPA02coco commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +    cy.url().should('not.include', 'custGroupId');
ご指摘ありがとうございます。
[7abdf12](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/7abdf12a00fc2d91c7242c825175baf67a1be3fe)にて修正しました。

2023-03-22 05:19 UTC, RPA02coco commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +      .type('-10000', { delay: 100 });
ご指摘ありがとうございます。
[14c11d7](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/14c11d757b7886fb902c21189fd2515f667ac433)にて類似箇所も含めて修正しました。

2023-03-23 01:06 UTC, RPA02coco commented on packages/kokoas-e2e/cypress.config.ts
> +      });
ご指摘ありがとうございます。
上記、[149895f](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/149895f7e5123849826fdc5bcd96632fac1cdcb5)と[809ed2b](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/809ed2bce204e8c83fa6bd0c8d84a67304ee6269)にて修正しました。
※ブランチの切り替え時にコミットしたため、2つに分かれてしまっています。見づらくてすみません。

2023-03-23 03:44 UTC, Lorenzras approved these changes
確認しました。

コメント残しましたが、変更しなくてもいいです。

2023-03-23 03:44 UTC, Lorenzras commented on packages/api-kintone/src/invoice/getInvoiceByEstDataId.test.ts
> +    );
変更不要です。chatGPTに生成してもらいました。

```suggestion
   const testDataId = 'KKB-C220020-01';
    expect(records.every(({ estimateLists }) => {
      return estimateLists.value.some(({ value: {
        dataId,
      } }) => dataId.value === testDataId);
    })).toBe(true);

```

2023-03-23 03:44 UTC, Lorenzras commented on packages/api-kintone/src/invoice/getInvoiceByEstDataId.ts
> +  const dataIdKey = 'dataId';
```suggestion
    const dataIdKey : keyof RecordType['estimateLists']['value'][number]['value'] = 'dataId';
```

長くなりますが、DB側の変更がある際、より安全になります。

2023-03-23 03:44 UTC, Lorenzras commented on packages/kokoas-e2e/cypress.config.ts
> +            });
この条件も、getInvoiceByEstDataId で組んだほうが、API呼び出し負担が少ないと思います。

2023-03-23 03:44 UTC, Lorenzras commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +      .check();
再利用できるセレクターが多数あります。でも、少ないので、変更不要です。

2023-03-27 02:59 UTC, RPA02coco commented on packages/api-kintone/src/invoice/getInvoiceByEstDataId.test.ts
> +    );
勉強になるので、修正させてもらいました。
[9b4c8f5](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/9b4c8f5c4eff0eccb8bbf7c34f2b18beb158a0d5)にて確認をお願いします。

2023-03-27 03:01 UTC, RPA02coco commented on packages/api-kintone/src/invoice/getInvoiceByEstDataId.ts
> +  const dataIdKey = 'dataId';
ご指摘ありがとうございます。
[9bdc0db](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/9bdc0dbff072f452d64065224494b980d8c8a52b)にて修正しました。

2023-03-27 04:15 UTC, RPA02coco commented on packages/kokoas-e2e/cypress.config.ts
> +            });
ご指摘ありがとうございます。
[05fc7b1](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/05fc7b116e4f7d4780fa91116251bf781616e01d)にて修正しました。

2023-03-27 04:41 UTC, RPA02coco commented on packages/kokoas-e2e/cypress.config.ts
> +            });
口頭でお聞きした件、[6ac5cf9](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/6ac5cf919fa191d79b828ee1a19f2f206a302ca4)にて修正しました。

2023-03-29 05:04 UTC, RPA02coco commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +      .check();
ご指摘ありがとうございます。
[16c120a](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/16c120a4f417138f9f49cba450130295e4e9d24f)にて修正しました。

なお、```cy.get('input[name*="exceedChecked"]')```は、初回が```not.exist```の状態のため、取得できずエイリアスに設定できないため、そのままにしてあります。
改善あればご教授お願いします。

2023-03-29 05:10 UTC, RPA02coco commented on packages/kokoas-e2e/cypress.config.ts
> +        },
[4afd5ab](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/4afd5ab761e8e38bc6380ed19df016f157ec9be7)にて、saveInvoicesをリファクタリングしました。

また、[1c0847f](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/1c0847fc75e87db77e79f5e7414baf41edbbd240)にてkintoneSDKを利用しての実装を試みましたが、エラーがとり切れなかったため、巻き戻しています([b364e4b](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/b364e4bfd5436833a702d95f8ab7ba69805a660f))。

日が空いてしまうため、一旦ログとして残させていただきます。

2023-03-30 03:22 UTC, Lorenzras commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +      .check();
そうですね。`alias ` 以外、セレクター(要素ではなく)を単純に[変数に格納](https://stackoverflow.com/questions/59460321/where-to-store-selectors-in-cypress-io)するか、頻繁が多くなったら、[command ](https://docs.cypress.io/api/cypress-api/custom-commands#docusaurus_skipToContent_fallback)化にするか、様々なやり方がありそうです。前より冗長なコードがだいぶ少なくなったので、これぐらいいいと思います 👌 。

2023-03-30 04:56 UTC, Lorenzras approved these changes
確認しました。コメントを残しましたが、変更不要です。

2023-03-30 04:56 UTC, Lorenzras commented on packages/kokoas-e2e/cypress.config.ts
> +        },
[1c0847f](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/1c0847fc75e87db77e79f5e7414baf41edbbd240) を拝見しました。

エラーは認証段階で失敗しているそうです。[kintoneのAPIの認証](https://cybozu.dev/ja/kintone/docs/rest-api/overview/authentication/)には様々な方法がありそうです。

ココアスは最初、APIトークン認証でしたが、セキュリティと保守性の観点で現在oAuth2がメインです。
APIの呼び出しはKintone内の場合、認証が不要です。

Kintone の updateAllRecordsの中身のコードを見ると、[bulkrequestというエンドポイント](https://cybozu.dev/ja/kintone/docs/rest-api/records/bulk-request/)を使っています。
ただ、bulkrequest はまだoauth2を対応していないので、basic認証かAPIトークン認証を使います。

DBの構成を更新していた時、似てる課題に遭ったので、basic認証を使った 'KintoneClientBasicAuth' を　作りました。

更新レコードは絶対に100以下なら、SDKのupdateRecordsの方がいいだと思います。updateRecordsは [recordsのエンドポイント](https://cybozu.dev/ja/kintone/docs/rest-api/records/update-records/)を使っているので、修正箇所が一番少ないです。

2023-04-11 05:06 UTC, RPA02coco commented on packages/api-kintone/src/invoice/getInvoiceByEstDataId.test.ts
> +      } }) => dataId.value === testDataId);
ご指摘ありがとうございます。
改善内容のため、変更入れさせていただきました。
[f726059](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/f7260597d5b2e7f55ed78e2a604d512c0ef80a8a)にて、ご確認をお願いいたします。

2023-04-11 05:11 UTC, RPA02coco commented on packages/kokoas-e2e/cypress/e2e/invoice/issueInvoiceAndDiscard.cy.ts
> +      .first()
ご指摘ありがとうございます。
[3acf797](https://github.com/Lorenzras/yumecoco-monorepo/pull/173/commits/3acf79794fd293f433a57261ec1181ecf68d2e7a)にて、履歴としてコメントアウトしました。
問題あれば行ごと削除します。

2023-04-12 03:10 UTC, RPA02coco commented on packages/kokoas-e2e/cypress.config.ts
> +        },
丁寧にありがとうございます！
同様のコメント、下にも表示(https://github.com/Lorenzras/yumecoco-monorepo/pull/173#discussion_r1152730725)がありましたので、そちらで対応させていただきます。

2023-04-13 02:26 UTC, RPA02coco commented on packages/kokoas-e2e/cypress.config.ts
> +        },
上記や型定義等、アドバイスありがとうございます。
KintoneClientBasicAuthを活用させていただき、修正しました。
ご確認をお願いいたします。

2023-04-13 02:46 UTC, Lorenzras approved these changes
E2Eテストすべて成功していると確認しました。マージしたら、今まで変更を本番へリリースします。

![image](https://user-images.githubusercontent.com/2501255/231634742-30b50fda-825a-4058-ae58-ce6039e8407b.png)

2023-04-13 02:53 UTC, merged