T279 - 見積のお金にかかわるフィールドの入力の挙動を改善
Lorenzras/yumecoco-monorepo pull request #177
Opened 2023-03-23 00:26 UTC by Lorenzras

## 変更

- 編集中にコンマを入れないようになりました。

## 理由

- 全角の場合、ダブってくるので、対応するのにブラウザによって挙動が違います。
- https://trello.com/c/BKbbYx8E

## 備考

- 全E2Eテストの実行：  `nx cypress:run kokoas-e2e`
- 計算にかかわるものテストは含めていないですが、計算に不具合がありましたら、当PRでE2Eテストを追加します。

2023-03-23 00:59 UTC, Lorenzras commented
![](https://github.trello.services/images/mini-trello-icon.png) [見積もり 数字入力問題](https://trello.com/c/BKbbYx8E/279-%E8%A6%8B%E7%A9%8D%E3%82%82%E3%82%8A-%E6%95%B0%E5%AD%97%E5%85%A5%E5%8A%9B%E5%95%8F%E9%A1%8C)

2023-03-23 03:02 UTC, RPA02coco requested changes
確認しました。
1点コメント残しましたので、確認をお願いします

2023-03-23 03:09 UTC, Lorenzras commented on packages/api-kintone/src/estimates/calculation/calculateEstimateSummary.ts
> +          .add(normalizedRowUnitPriceBeforeTax)
いいえ、コンフリクト解消の際に見落としました。ありがとうございます！  84ee36b1 にて対応しました。

2023-03-24 02:39 UTC, Lorenzras commented
ブラウザーバージョンによって、挙動安定しない可能性があるので、調査中のため、開発中のコメントを残しています。
数か月後、不具合報告なかったら、削除します。

2023-03-27 02:08 UTC, RPA02coco approved these changes
確認しました。
動作も問題ないと思います

2023-03-27 02:10 UTC, merged