ショートカットキー修正
Lorenzras/yumecoco-monorepo pull request #185
Opened 2023-03-31 06:01 UTC by Lorenzras

## 変更

- 行追加を insert から、ctrl + i にしました。
- ラベルを追加

## 変更理由

- 高橋さんから指示を受けながら、やりました。

2023-04-05 07:31 UTC, Lorenzras commented
正式的な指示はまだ来てないので、ココアスを続行します。

2023-04-11 04:51 UTC, RPA02coco requested changes
確認しました。
動作には問題ないと思います。
口頭で確認した部分をコメントに残しましたので、対応お願いします！

2023-04-11 04:51 UTC, RPA02coco commented on packages/kokoas-e2e/cypress/e2e/estimate/shortcuts.cy.ts
> +    cy.log('最終行は一つしかないなら、フォーカスは仮想業の行に移動する');
```suggestion
    cy.log('最終行は一つしかないなら、フォーカスは仮想業の行に移動する');
```

```最終行は一つしかないなら、フォーカスは仮想行に移動する```
の誤記かと思います。
ご確認をお願いします。

2023-04-12 01:05 UTC, RPA02coco approved these changes
修正および変更を確認しました。
問題ないと思います。

2023-04-12 23:51 UTC, merged