ANDPADの入金一覧情報バックアップを更新します
Lorenzras/yumecoco-monorepo pull request #305
Opened 2023-05-23 05:49 UTC by RPA02coco

## 変更

1. ANDPADの入金一覧のバックアップ用アプリを更新する処理を実装します

## 理由

1. [変更理由](https://trello.com/c/bAhGWqpl)

## テスト

- 実装方法検討中

2023-07-07 04:46 UTC, YokoHayakawa commented
andpadからexcelファイルをダウンロードし、csvに変換するところまでを実装しました。
kintoneへの保存処理は別PRにて対応します。

2023-07-10 01:11 UTC, Lorenzras requested changes
確認しました。後小さい変更です。

以下の変更を頂けるとより分かりやすいです。
downloadPaymentfile →　downloadPaymentsData

2023-07-10 01:11 UTC, Lorenzras commented on packages-automation/auto-paymentAlert/src/downloadPaymentList/downloadPaymentfile.test.ts
> +    );
downloadFileの単体テストになりますので、downloadPaymentfileの単体テストに変えましょう。

2023-07-10 02:13 UTC, YokoHayakawa commented on packages-automation/auto-paymentAlert/src/downloadPaymentList/downloadPaymentfile.test.ts
> +    );
失礼しました。
[a3a24b6](https://github.com/Lorenzras/yumecoco-monorepo/pull/305/commits/a3a24b6e220c4c552f89cf2e7fe917ad251b8e72)にて修正しましたので、ご確認をお願いします。

2023-07-10 02:14 UTC, YokoHayakawa commented
ご指摘ありがとうございます。
[b4e0309](https://github.com/Lorenzras/yumecoco-monorepo/pull/305/commits/b4e0309c0a46794dda2247de7951dd5a98e8182a)にて、フォルダおよびファイル名の変更を行ってます。
ご確認をお願いします。

2023-07-10 02:30 UTC, Lorenzras requested changes
確認しました。
downloadPaymentDataの単体テストのアサーションはいい方法ですね。
参考になりました。

2023-07-10 02:30 UTC, Lorenzras commented on package.json
> +    "@types/puppeteer": "^7.0.4",
気づくの遅くなりました。
これが不要になりました。
puppeteer（google）　が正式な型定義を本パッケージとリリースされましたので、不要になりました。

マスターで、３週間前、削除済みです。

https://www.npmjs.com/package/@types/puppeteer

2023-07-10 02:47 UTC, Lorenzras approved these changes
確認！しました！

2023-07-10 02:48 UTC, YokoHayakawa commented on package.json
> +    "@types/puppeteer": "^7.0.4",
ありがとうございます。
リンク先も確認させてもらいました。

2023-07-10 02:51 UTC, merged