hotfix-契約に関わる金額をすべて編集出来るように
Lorenzras/yumecoco-monorepo pull request #312
Opened 2023-05-25 02:12 UTC by Lorenzras

## 変更

### 前

### 後

![image](https://github.com/Lorenzras/yumecoco-monorepo/assets/2501255/1091efa9-14cc-4660-a150-5c08ba16cf02)

## 理由

1. 沖永店長から依頼は

## テスト

- 実行方法

2023-05-26 05:40 UTC, RPA02coco requested changes
コメント残しましたので、ご確認をお願いします。

2023-05-26 05:40 UTC, RPA02coco commented on packages/kokoas-client/src/hooks/useNumberCommaField.ts
> +      console.log('COMPOSITION_END', e.nativeEvent, el.value, halfWidth);
コンソール残っていますが、問題ないでしょうか？

2023-05-26 05:40 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projContractV2/fields/ProfitRate.tsx
> +              }
```suggestion
                const {
                  amountBeforeTax,
                  profit,                  
                  costPrice,
                } = calculateAmount({
                  taxRate: taxRate,
                  amountAfterTax: totalContractAmtAfterTax,
                  profitRate: profitRate / 100,
                });

                setValue('totalContractAmtBeforeTax', amountBeforeTax || 0);
                setValue('totalProfit', profit || 0);
                setValue('costPrice', costPrice || 0);
              }
```

粗利率が変更された際、原価が更新されていませんでした。
こちらで動作確認した際には、上記変更でうまくいきそうでしたが、
react-hook-formに対してまだ経験が浅い為、処理の確認をお願いします。

2023-05-26 05:42 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projContractV2/parts/AmountDetails.tsx
すみません、変更前のコメントが残ってしまっていましたので、こちらで解決させてもらいました。

2023-05-26 05:43 UTC, Lorenzras commented on packages/libs/src/calculateAmount.ts
> +    }
ありがとうございます。そのまま適用しました。

2023-05-29 00:43 UTC, Lorenzras commented on packages/libs/src/calculateAmount.test.ts
> +    expect(result.costPrice).toEqual(80);
あった方がいいですね。ありがとうございます。

現在、とても簡単なテストケースですが、変な数字になるケースがあれば、追加をお願いします。

2023-05-29 03:18 UTC, Lorenzras commented on packages/kokoas-client/src/hooks/useNumberCommaField.ts
> +      console.log('COMPOSITION_END', e.nativeEvent, el.value, halfWidth);
ありがとうございます。対応しました。

2023-05-29 03:19 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projContractV2/fields/ProfitRate.tsx
> +              }
助かりました！そのまま適用しました。ありがとうございます。

2023-05-29 04:52 UTC, RPA02coco requested changes
1点修正漏れと思われる箇所がありましたので、確認をお願いします。

2023-05-29 04:52 UTC, RPA02coco commented on packages/libs/src/calculateAmount.ts
> +  profit?: number,
'''粗利率'''→'''粗利額'''
誤記修正漏れていたようです。確認お願いします。

2023-05-29 04:54 UTC, Lorenzras commented on packages/libs/src/calculateAmount.ts
> +  profit?: number,
ありがとうございます！修正しました。

2023-05-29 04:57 UTC, RPA02coco approved these changes
修正確認しました。
ご対応ありがとうございます。

2023-05-29 18:42 UTC, merged