hotfix-小○さんを最終CCに追加する
Lorenzras/yumecoco-monorepo pull request #314
Opened 2023-05-25 05:34 UTC by Lorenzras

## 変更

1. 小○さんを最終CCに追加する

## 理由

1. 高橋さんから依頼

2023-05-30 04:46 UTC, YokoHayakawa requested changes
コメント残しましたので、確認をお願いいたします。

2023-05-30 04:46 UTC, YokoHayakawa commented on packages/kokoas-server/src/handleRequest/reqSendContractDirectV2/processContractV2.test.ts
テスト実行がエラーになってしまいました。
おそらくngrokがエラーページに飛ぶせいだとは思いますが、改めて確認させてください。

2023-05-30 04:46 UTC, YokoHayakawa commented on packages/kokoas-server/src/handleRequest/reqSendContractDirectV2/makeEnvelopeV2.ts
> +  // 小出さん
```経理(最終確認者）```等はどうでしょうか。
個人名よりは良いのかな、と思いました。

2023-05-31 00:02 UTC, Lorenzras commented on packages/api-kintone/src/employees/getContractCheckers.ts
> +    'uuid = "44e0d1ae-752e-4ef4-8542-c91495b52b52"',
ありがとうございます。そうですね。頻繁に変わるものなら、柔軟性を持たせたほうがいいですね。
その仕様になった時、別PRでマスター設定に追加しようと思います。

当面、小出さんを追加するという仕様になっていますが、この要件を変わるタイミングで、どの経理（東・西）などか設定出来るようにします。

2023-05-31 00:17 UTC, Lorenzras commented on packages/api-kintone/src/employees/getContractCheckers.ts
> +  const subAccounting = records.find(({ uuid }) => uuid.value === '44e0d1ae-752e-4ef4-8542-c91495b52b52' );
ありがとうございます。uuidが2カ所にあると気づきませんでした。
最初はuuid確実にあると思い、その行のテストはありませんでした。

今もそのテストがいるかどうか悩んでいますが、あっても損はないので、重複を修正しました。

2023-05-31 00:23 UTC, Lorenzras commented on packages/api-kintone/src/employees/getContractCheckers.ts
> +  if (!subAccounting) throw new Error(`S経理の情報取得ができませんでした。${subAccounting}`);
なんの経理かかわからなくて、Sにしちゃいました。
由来は副経理という思い込みで、英語のsub accountantから来ました。w

開発者のための、エラーですが、ユーザに出ることがあるので、
推薦をそのままに摘要しました。ありがとうございます。

2023-05-31 00:27 UTC, Lorenzras commented on packages/kokoas-server/src/handleRequest/reqSendContractDirectV2/makeEnvelopeV2.ts
> +  // 小出さん
当要件に思い切り合わせました。w

修正しました。ありがとうございます。

2023-05-31 00:29 UTC, Lorenzras commented on packages/kokoas-server/src/handleRequest/reqSendContractDirectV2/processContractV2.test.ts
了解です！

2023-05-31 01:59 UTC, YokoHayakawa commented on packages/kokoas-server/src/handleRequest/reqSendContractDirectV2/processContractV2.test.ts
ご教授ありがとうございました！
確認できたため、コメント閉じさせていただきます。

2023-05-31 01:59 UTC, YokoHayakawa approved these changes
修正確認しました。
ご対応ありがとうございます。

2023-05-31 02:03 UTC, merged