hotfix-契約の内容：店舗名と会社情報を更新-ras
Lorenzras/yumecoco-monorepo pull request #321
Opened 2023-05-26 05:27 UTC by Lorenzras

## 変更

1. KKG-C202299 かた　大林-C202299になりました。
2. 会社情報は本社じゃなく、店舗になりました。

## 理由

1. 小出さんから依頼

## テスト

- 単体テスト

2023-05-26 05:28 UTC, Lorenzras commented
会社名は店舗の正式名称でいいか確認中

2023-05-31 03:06 UTC, YokoHayakawa requested changes
コメント残しましたので、ご確認をお願いします。

2023-05-31 03:06 UTC, YokoHayakawa commented on packages/kokoas-server/src/handleRequest/reqSendContractDirectV2/generateContractPdfV2.ts
> +  );
```suggestion
  // 会社住所 上
  drawText(
    firstPage,
    companyAddress,
    {
      x: companyX,
      y: companyY - companyLH,
      font: msChinoFont,
    },
  );
```

2023-05-31 03:06 UTC, YokoHayakawa commented on packages/kokoas-server/src/handleRequest/reqSendContractDirectV2/generateContractPdfV2.ts
> +  );
```suggestion
  // 会社住所　下
  drawText(
    firstPage,
    companyAddress2,
    {
      x: companyX,
      y: companyY2,
      font: msChinoFont,
    },
  );
```

契約書下部の住所表記は、「住所」+「ハウスドゥ 〇〇〇〇店」とする、とのことでしたので、
```companyAddress```の中身自体を変更する必要があるかと思います。

2023-05-31 03:06 UTC, YokoHayakawa commented on packages/kokoas-server/src/handleRequest/reqSendContractDirectV2/getContractDataV2.ts
> +    companyAddress: `${companyAddress.value} ${storeName.value}`,
```suggestion
    companyAddress: `${companyAddress.value} ${storeName.value}`,
    companyAddress2: `${companyAddress.value} ハウスドゥ ${storeName.value}`,
```

1案なので、修正はこの通りである必要はないです。実装方法はお任せします。
契約書上部と下部で住所の表記が異なるとのことです。

2023-05-31 03:08 UTC, Lorenzras commented on packages/kokoas-server/src/handleRequest/reqSendContractDirectV2/generateContractPdfV2.ts
> +  );
ありがとうございます。そのまま適用しました。

2023-05-31 03:09 UTC, Lorenzras commented on packages/kokoas-server/src/handleRequest/reqSendContractDirectV2/generateContractPdfV2.ts
> +  );
ありがとうございます。そのまま適用しました。

2023-05-31 03:29 UTC, Lorenzras commented on packages/kokoas-server/src/handleRequest/reqSendContractDirectV2/getContractDataV2.ts
> +    companyAddress: `${companyAddress.value} ${storeName.value}`,
ありがとうございます。そのまま適用しました。

2023-05-31 04:03 UTC, YokoHayakawa approved these changes
修正確認しました。
問題ないと思います。

2023-05-31 04:05 UTC, merged