絞り込みにここすも担当者の選択肢を追加しました。
Lorenzras/yumecoco-monorepo pull request #353
Opened 2023-06-05 01:27 UTC by Lorenzras

##　派生元

- #346 

## 変更

1. 絞り込みにここすも担当者の選択肢を追加しました。

## 理由

1. close #352

2023-06-08 05:20 UTC, Lorenzras commented
ドラフトに戻しました。

2023-06-08 05:29 UTC, YokoHayakawa requested changes
コメント残しましたので、確認をお願いします。

2023-06-08 05:29 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projSearch/sections/filter/filterForm/CocoOfficer.tsx
> +
工務のメニューが2つになってしまっています。
こちらは削除で良いかと思います。

2023-06-08 05:56 UTC, Lorenzras commented on packages/api-kintone/src/employees/getEmployees.ts
> +  console.log('QueryArray', queryArray);
対応中でした。ありがとうございます。削除しました。

2023-06-08 05:57 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projSearch/sections/filter/filterForm/CocoOfficer.tsx
> +
ありがとうございます。領域に変えました。

2023-06-09 05:50 UTC, YokoHayakawa requested changes
コメント残しましたので、確認をお願いします。

2023-06-09 06:21 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projSearch/sections/filter/filterForm/CocoOfficer.tsx
> +  console.log('data', data);
対応しました。

2023-06-09 06:21 UTC, Lorenzras commented on packages/types/src/dtsgen/db.employees.d.ts
> +    役職_0: kintone.fieldTypes.DropDown;
ありがとうございます。対応しました。

2023-06-10 01:48 UTC, merged