請求入力：顧客検索に変更する 早川
Lorenzras/yumecoco-monorepo pull request #43
Opened 2022-11-29 02:56 UTC by RPA02coco

**変更**

 - 工事検索から、顧客検索に変更する
 - 契約一覧表を工事ごとにテーブルで表示する
 
---

**変更理由**

要件変更による
詳細は[カードT190](https://trello.com/c/ccKTgw6W)参照

---

**関連**

[PR40](https://github.com/Lorenzras/yumecoco-monorepo/pull/40)に依存します

2022-12-13 01:55 UTC, RPA02coco commented
フォントファイルが勝手に書き換わってしまうため、「.gitattributes」にも変更を加えています。
変更内容に問題ないか、ご確認をお願いいたします。

2022-12-15 03:28 UTC, Lorenzras requested changes
見た目の方はいい感じですね。

コード確認しました。
コメント対応お願いします。:rocket:

2022-12-15 03:28 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/helper/estimatesSplit.ts
> +  return sortContracts;
以下はいかがですか。当関数と同じ仕様にしましたが、気付いていないものがあるかもしれません。

```Typescript
 const splitEstimateByProjId = (estimates: TMaterials[]) => {

  const groupedByProjId =  estimates.reduce((acc, cur) => {
    if (typeof acc[cur.projId] === 'undefined') {
      acc[cur.projId] = [];
    }
    acc[cur.projId].push(cur);
    return acc;
  }, {} as Record<string, TMaterials[]>);

  return Object.values(groupedByProjId);
}
```

2022-12-15 03:28 UTC, Lorenzras commented on packages/kokoas-server/.gitattributes
> +*.ttf binary
当変更は　レポジトリのルートの　`.gitattributes`　追加すると同じ現象でしょうか。

2022-12-15 04:08 UTC, RPA02coco commented on packages/api-kintone/src/estimates/paymentListCreate.ts
> +  };
paymentTypeList には、契約時にチェックを入れている支払い種別(ex.着工金、中間金 など)をカンマ区切りで格納します。
paymentamtPerType には、支払い種別ごとの支払金額をカンマ区切りで格納します。

どちらも請求入力欄で、請求金額の入力を行う際のサポートとして使用する予定です。

ただし、paymentamtPerTypeがpayment**A**mtPerTypeの誤記のため、修正します。

2022-12-15 04:10 UTC, RPA02coco commented on packages/api-kintone/src/estimates/paymentListCreate.ts
> +export const paymentListCreate = (estimateRecord: RecordType) => {
承知しました。
すみません、命名ルール理解しきれていませんでした。。。
修正します。

2022-12-15 04:15 UTC, RPA02coco commented on packages/api-kintone/src/invoice/getInvoiceByCustGroupId.ts
> +  const custGroupIdKey: KProjestimates = 'custGroupId';
承知しました。
修正します。

2022-12-15 04:29 UTC, RPA02coco commented on packages/kokoas-client/src/hooksQuery/useInvoiceTotalByCustGroupId.ts
> +      }, [] as EstimateList[]);
承知しました。
foreachで実装修正します。

2022-12-15 04:35 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/FormikInvoice.tsx
> +        const handleSave = () => setTimeout(() => {
失礼しました。作り込み段階で誤って埋め込んでいると思われます。
setTimeoutは不要と思いますので、削除します。

2022-12-15 04:35 UTC, Lorenzras commented on packages/api-kintone/src/estimates/paymentListCreate.ts
> +  };
請求入力欄ですね。承知しました。

2022-12-15 04:39 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/DisplayAmount.tsx
> +      <Grid item xs={12} md={6}>
本件、完全にコーディングのミスです。
ただし、要件変更により次PRで本コンポーネントは削除するため、このPRでは一旦このままとさせていただきます。

2022-12-15 04:41 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/hooks/useResolveParams.ts
> +    const newEstimates = contracts ? estimatesSort(contracts) : undefined;
承知しました。ご指摘ありがとうございます。
修正します。

2022-12-15 04:42 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/hooks/useResolveParams.ts
> +      if (custData && contracts) {
修正します

2022-12-15 04:47 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/EstimatesTable.tsx
> +                    idx += 1;
コンポーネント「EstimateTableBody」内の、請求に使用する(isForPayment)のチェックボックスをformik化するのに使用しています。
工事ごとに契約一覧テーブルを分ける際に、契約一覧テーブルを2次元配列化しているため、mapオプションのインデックスが使用できなくなってしまったため、ここでインデックスを作り直しています。

2022-12-15 04:48 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/EstimatesTableBody.tsx
> +          estimateRow.dataId.split('-')[2]
承知しました。ありがとうございます！
修正します。

2022-12-15 04:51 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/EstimatesTableBody.tsx
> +          estimateRow.dataId.split('-')[2]
上記の通り修正したところ、末尾1文字になってしまったため、下記の通り修正しております。

estimateRow.dataId.split('-').at(-1)

2022-12-15 04:54 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/helper/estimatesSort.ts
> +export const estimatesSort = ({
私の命名ルールの理解不足のため、問題ないです。
修正します

2022-12-15 04:55 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/helper/estimatesSort.ts
> +  }[];
修正します。

2022-12-15 05:01 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/helper/estimatesSort.ts
> +  }, [] as EstimatesList[]);
承知しました。
修正します。

2022-12-15 05:08 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/helper/estimatesSort.ts
> +  }, [] as EstimatesList[]);
確認したところ、mapで対応できました。
修正します。

2022-12-15 05:14 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/helper/estimatesSort.ts
> +  return estimatesBkup;
承知しました。
今確認した限りで、estimatesBkupは不要と思いましたので、合わせて修正しました。

2022-12-15 05:15 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/helper/estimatesSplit.ts
> +export const estimatesSplit = (estimates: TMaterials[]) => {
承知しました。
修正します。

2022-12-15 05:21 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/helper/estimatesSplit.ts
> +  let sortContracts = estimatesCopy.reduce((acc, cur, idx) => {
確認しました。
estimatesCopy分の処理は不要と思いますので、estimatesBkupのみ残して実装修正します。
(array.sliceの処理がうまく実装出来なかったときに、誤解したままでした。)

2022-12-15 05:34 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/helper/estimatesSplit.ts
> +  return sortContracts;
ありがとうございます。
コード(主に Object.values )を確認させていただきました。
この内容で実装修正させていただきます。

2022-12-15 05:40 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/EstimatesTable.tsx
> +                    idx += 1;
そういうことですね。分かりました。

以下はいかがですか。

```Typescript
...
let idx = 0;

...
{arr.map((row) => {
  idx ++;
...
```

2022-12-15 05:41 UTC, RPA02coco commented on packages/kokoas-server/.gitattributes
> +*.ttf binary
今確認したところ、ファイルの変更を巻き戻してもフォントファイルに変更は入りませんでした。
以前はルート側の設定がうまく読み込めていなかった？？と推定してファイル戻しておきます。

2022-12-15 05:54 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/EstimatesTableBody.tsx
> +          estimateRow.dataId.split('-')[2]
split抜けて、失礼いたしました。頭のコンパイラーはもう劣化しています。ｗ

2022-12-15 05:59 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/fieldComponents/EstimatesTable.tsx
> +                    idx += 1;
口頭で確認させて頂いたとおり、formにidxを追加することで対応し、idxは削除しました。
アドバイスありがとうございます！

2022-12-15 06:09 UTC, Lorenzras requested changes
この変更、確認しました。

2022-12-15 06:09 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projInvoice/helper/sortEstimatesByProjId.ts
> +  records.map((cur, idx) => {
```suggestion
  const convertedEstimates = records.map((cur, idx) => {
  
  // convertedEstimates.push(newData);　はなくなります。
```

2022-12-16 02:10 UTC, Lorenzras commented on packages/kokoas-client/src/hooksQuery/useInvoiceTotalByCustGroupId.ts
> +      }, [] as EstimateList[]);
```suggestion
      // 見積もり(契約)毎の請求済み金額を取り出す処理
      const totalInvoice = data.records.reduce((acc, cur) => {
        const estimateList = cur.estimateLists.value;

       // const estimateObj = [] as EstimateList[];
        estimateList.forEach((estimate) => {

          acc.push({
            dataId: estimate.value.dataId.value,
            billedAmount: estimate.value.amountPerContract.value,
          });
        });

       // acc = acc.concat(estimateObj);
        
        return acc;

      }, [] as EstimateList[]);
```

2022-12-16 02:24 UTC, Lorenzras requested changes
確認しました。

2022-12-16 02:25 UTC, RPA02coco commented on packages/kokoas-client/src/pages/projInvoice/helper/sortEstimatesByProjId.ts
> +  records.map((cur, idx) => {
ご指摘ありがとうございます。
修正します。

2022-12-16 02:28 UTC, RPA02coco commented on packages/kokoas-client/src/hooksQuery/useInvoiceTotalByCustGroupId.ts
> +      }, [] as EstimateList[]);
ご指摘ありがとうございます。
上記の内容で修正します。

2022-12-16 03:07 UTC, Lorenzras approved these changes
確認しました。

2022-12-16 04:03 UTC, merged