kintoneの入金一覧アプリへandpadの入金情報をアップロードする
Lorenzras/yumecoco-monorepo pull request #503
Opened 2023-07-07 04:58 UTC by YokoHayakawa

## 変更

1. #305  にて保存したandpadの入金一覧ファイルの内容を、kintoneへアップロードします。

## 理由

1. andpadの入金一覧情報を活用してアラート機能を実装するため。その下準備として。
2. fix #502 

## テスト

- 実行方法：検討中

2023-07-13 05:27 UTC, Lorenzras requested changes
確認しました。よろしくお願いします。

2023-07-13 05:27 UTC, Lorenzras commented on packages/config/src/appIds.ts
> +  payments : 233,
Andpadで作成されたデータなので、andpadPaymentsにしました。ｗ
いかがですか。

2023-07-13 05:27 UTC, Lorenzras commented on packages-automation/auto-kintone/config.ts
> +};
packages\config\src\appIds.ts にもあります。

依存している箇所では使えるかもしれません。

2023-07-14 02:57 UTC, YokoHayakawa commented on packages-automation/auto-kintone/config.ts
> +};
ご指摘ありがとうございます。
検討不足だっただけですので、[4fbdfbf](https://github.com/Lorenzras/yumecoco-monorepo/pull/503/commits/4fbdfbfb8dd3471109fa69180b9557d9339eb595)で参照場所を修正しています。
ご確認をお願いします。

2023-07-14 03:03 UTC, YokoHayakawa commented on packages/config/src/appIds.ts
> +  payments : 233,
すみません、andpadPaymentsを見落としていました。
[6b60649](https://github.com/Lorenzras/yumecoco-monorepo/pull/503/commits/6b6064920f399b9b228318151982c4d722487b14)および[50befd4](https://github.com/Lorenzras/yumecoco-monorepo/pull/503/commits/50befd42b42c50ba1056a3d9d73f6e99fd58f724)にて、重複分の削除をしました。

2023-07-14 04:00 UTC, YokoHayakawa commented
口頭でお伝えしていた件を2点修正しました。
 - ダウンロードアドレス:[3e06ae3](https://github.com/Lorenzras/yumecoco-monorepo/pull/503/commits/3e06ae37eb9f0122a2c822888b0945629e206c0e)
 - フォルダ名の修正:[be3330e](https://github.com/Lorenzras/yumecoco-monorepo/pull/503/commits/be3330e4e73554c8225e5560cd447ba3bd4d2727)
 - フォルダ名変更に伴う調整:[e8f9e17](https://github.com/Lorenzras/yumecoco-monorepo/pull/503/commits/e8f9e173f91e8101242582f3e5a441981be18336)

ご確認をお願いします。

2023-07-18 01:02 UTC, YokoHayakawa commented
@Lorenzras 
typesの修正ありがとうございます。
影響箇所の修正と不要なファイル削除をしました。
ご確認お願いします。

2023-07-18 01:12 UTC, Lorenzras approved these changes
確認しました！

2023-07-18 01:28 UTC, merged