削除した工事レコードは検索に出さないようにする
Lorenzras/yumecoco-monorepo pull request #57
Opened 2022-12-15 04:12 UTC by Lorenzras

## 変更

- 削除したものは顧客詳細画面の工事情報からも非表示にする。
- 工事情報の見積りを「契約金額（税込み）」と「利益額・率」にする。

## 変更理由

- [T208](https://trello.com/c/S9mM1bqg)

2022-12-15 04:38 UTC, Lorenzras commented
![](https://github.trello.services/images/mini-trello-icon.png) [工事情報の削除・表示の変更](https://trello.com/c/S9mM1bqg/208-%E5%B7%A5%E4%BA%8B%E6%83%85%E5%A0%B1%E3%81%AE%E5%89%8A%E9%99%A4%E3%83%BB%E8%A1%A8%E7%A4%BA%E3%81%AE%E5%A4%89%E6%9B%B4)

2022-12-16 03:01 UTC, RPA02coco requested changes
確認しました。
要件変更の内容で誤解もあったため、別途お伝えします。

2022-12-16 03:49 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projRegister/sections/ConstructionInfo/ConstractList.tsx
> +  const tableHeadder = ['ステータス', 'id', '契約日', '利益額・率'];
ありがとうございます。要件の勘違いのため、元に戻しました。

2022-12-16 04:21 UTC, RPA02coco requested changes
確認しました。
コメント残しましたので、ご確認ください。

2022-12-16 04:21 UTC, RPA02coco commented on packages/kokoas-client/src/pages/customer/search/parts/detailsDialog/projects/EstimatesListItem.tsx
> +          />
「作成日」と「ID」は、従来のcaption程度の文字の大きさで、実装とのことです。
お願いします！

2022-12-16 04:47 UTC, Lorenzras commented on packages/kokoas-client/src/pages/customer/search/parts/detailsDialog/projects/EstimatesListItem.tsx
> +          />
対応しました。口頭で確認した内容も実装しました。

2022-12-16 05:38 UTC, RPA02coco approved these changes
修正確認しました！

2022-12-16 05:38 UTC, merged