契約処理の改修
Lorenzras/yumecoco-monorepo pull request #60
Opened 2022-12-17 07:29 UTC by Lorenzras

## 変更内容

- 

## 変更理由

-

2022-12-17 07:31 UTC, Lorenzras commented
![](https://github.trello.services/images/mini-trello-icon.png) [Docusign - 処理改修](https://trello.com/c/v5BDM1E8/210-docusign-%E5%87%A6%E7%90%86%E6%94%B9%E4%BF%AE)

2022-12-19 03:50 UTC, RPA02coco requested changes
確認しました。
動作も問題ありませんでした。
テスト環境の設定、教えて頂きありがとうございます。

コメント残しましたので、ご確認をお願いいたします。

2022-12-19 03:50 UTC, RPA02coco commented on packages/kokoas-server/src/api/docusign/getEnvelope.ts
> +  console.log(apiClient);
コンソールが残っていますが、問題ないでしょうか？

2022-12-19 03:51 UTC, Lorenzras commented on packages/kokoas-client/src/lib/jaEnvStatus.ts
> +      };
了解です！

2022-12-19 03:52 UTC, Lorenzras commented on packages/kokoas-server/src/api/docusign/getEnvelope.ts
> +  console.log(apiClient);
サーバ側で大丈夫です。

2022-12-19 03:58 UTC, RPA02coco approved these changes
確認しました。

2022-12-19 03:58 UTC, merged