K185-react-imaskをreact-number-formatに移行しました。
Lorenzras/yumecoco-monorepo pull request #649
Opened 2023-09-12 06:04 UTC by Lorenzras

## 変更

1. react-imaskをreact-number-formatに移行しました。

## 理由

1. 最新バージョンあっても、ランタイムエラーがあるからです。

## テスト

- 当面なし

2023-09-14 12:17 UTC, Lorenzras commented
@YokoHayakawa よろしくお願いします。

2023-09-15 03:06 UTC, YokoHayakawa requested changes
確認しました。
基本的な動作やコーディングには問題ないと思います。
懸念点についてコメント残しましたので、改めて相談させて下さい

2023-09-15 03:06 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/custGroup/sections/customersInput/address/postal/MaskedPostal.tsx
全角入力の状態で数字を入力してしまうと、数字が半角で2つ入力されてしまいました。
以前も日本語特有の問題として完璧には処置できないという結論にはなっていると思いますが、今回はどこまで対応するか相談したいです。
個人的には、前回よりも顕著にわかりやすくなっているので、前回と同等レベルまで修正するか、「半角で入力してください」等の補助的なメッセージを出す方が親切かなと思っています。

2023-09-15 03:06 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projRegisterV2/sections/projectLocation/postalField/MaskedPostal.tsx
custGroupのmaskedPostal.tsxと同様、全角入力の対応について確認したいです。

2023-09-15 03:51 UTC, Lorenzras commented
@YokoHayakawa 3日前のPR気づいたくれました！ありがとうございます！

そうですね。Andpadの郵便番号にも全角を入れると、郵便番号で検索機能しないです。

直そうとして、パソコン設定によって挙動がことなるので、全角の数字自体を廃止する動きがあります。

https://laugh-raku.com/archives/25550

メッセージは当PRと別用件なので、別依頼として対応しましょう。

2023-09-15 03:55 UTC, YokoHayakawa commented
>3日前のPR気づいたくれました！ありがとうございます！

完全に見落としてました…
申し訳ないです…
今朝気付けて良かったですf^_^;

>メッセージは当PRと別用件なので、別依頼として対応しましょう。

承知しました！

2023-09-15 03:55 UTC, YokoHayakawa approved these changes

2023-09-15 04:05 UTC, Lorenzras commented
ありがとうございます。後ほどmasterにマージさせますが、時間があれば、本番へ実装お願いします。

なお、masterにビルド問題がありましたら、別PRで修正をお願いします。

GithubアプリでポチッとApproveします。

⭐️ npm i が必要です。

2023-09-15 04:18 UTC, Lorenzras commented
@YokoHayakawa 

Conflictがありました。次回対応します。

2023-09-15 04:20 UTC, YokoHayakawa commented
承知しました。
では、今回も対応はお任せします。
よろしくお願いします。

2023-09-18 08:17 UTC, merged