リマインダーレコードの登録処理を追加
Lorenzras/yumecoco-monorepo pull request #673
Opened 2023-09-22 05:19 UTC by YokoHayakawa

## 変更

1. 契約書からの通知対象レコードの抽出時に、リマインダーアプリへの登録処理を追加します

## 理由

1. リマインダー登録の事前準備のため

## テスト

- createPaymentAlert.test.tsを実行

2023-09-22 07:11 UTC, Lorenzras approved these changes
確認しました！

`DBPaymentreminder`　ですが、2カ所でAliasを設定されています。

- src/dbKintone.ts
- ./config.ts

どっちかにした方いいと思います。

2023-09-22 07:12 UTC, Lorenzras requested changes
よろしくお願いします。

2023-09-25 02:20 UTC, YokoHayakawa commented on packages-automation/auto-paymentAlert/src/api-kintone/addPaymentReminder.ts
> +export const addPaymentReminder = (params: AddPaymentReminder[]) => {
ご指摘ありがとうございます。
[9161234](https://github.com/Lorenzras/yumecoco-monorepo/pull/673/commits/9161234c1bac83215df1dbc2a34a16c8ae17e7b8)にて型名修正に合わせた内容で修正しています。

2023-09-25 02:20 UTC, YokoHayakawa commented on packages-automation/auto-paymentAlert/src/api-kintone/addPaymentReminder.ts
>  };
ご指摘ありがとうございます。
[9161234](https://github.com/Lorenzras/yumecoco-monorepo/pull/673/commits/9161234c1bac83215df1dbc2a34a16c8ae17e7b8)にて修正しましたので、ご確認をお願いします。

2023-09-25 02:21 UTC, YokoHayakawa commented on packages-automation/auto-paymentAlert/src/helpers/convertReminderToKintone.ts
> +  const kintoneData: AddPaymentReminder[] = paymentReminderJson.map(({
ご指摘ありがとうございます。
[9161234](https://github.com/Lorenzras/yumecoco-monorepo/pull/673/commits/9161234c1bac83215df1dbc2a34a16c8ae17e7b8)にて修正しました。
ご確認をお願いします。

2023-09-25 02:21 UTC, YokoHayakawa commented
ご指摘ありがとうございます。
./config.tsに集約する形で修正しました。
ご確認をお願いします。

2023-09-25 03:02 UTC, Lorenzras approved these changes
確認しました！LGTM！

2023-09-25 03:02 UTC, Lorenzras commented on packages-automation/auto-paymentAlert/src/api-kintone/config.ts
> +export type RecordKey = KPaymentReminder;
変更不要:

PaymentReminderしかないので、`RecordType` と`RecordKey`に再宣言せず、直接IPaymentReminderを利用するのもいいとかもしれません。

appIdも当パッケージのrootのconfigに宣言するのもいいかもしれません。

当パッケージのapiが多くなる見込みなら、また構成が変わると思います。

別話ですが、Angularのような[Opinionated](https://izumisy.work/entry/2019/07/10/112315)なフレームワークだと、構成が決まっていて最初から複雑になっています。

生のNodeJsやReactのようなものだと、Less Opinionatedで 構成はプロジェクトと進化していきます。

ココアスのコード参考するのもいいですが、まだシンプルで行けるならそれでよく、課題に応じて構成を調整させていいと思います。

2023-09-25 04:28 UTC, YokoHayakawa commented on packages-automation/auto-paymentAlert/src/api-kintone/config.ts
> +export type RecordKey = KPaymentReminder;
ありがとうございます。勉強になります。
つい自分の慣れた分かりやすい構成に逃げてしまいがちですが、確かに今は小規模なので、構成を固める必要はなさそうですね。
まだ構成に対する検討は力不足で出来ていないので、これを機に対応してみます。

本PRは一度閉じさせていただいて、#682 にて実装検討します。

2023-09-25 04:28 UTC, merged