Fix dev ras
Lorenzras/yumecoco-monorepo pull request #73
Opened 2022-12-22 00:26 UTC by Lorenzras

## 変更内容

## 変更理由

2022-12-22 04:31 UTC, RPA02coco requested changes
確認しました。
コメント残していますので、ご確認ください。

2022-12-22 04:32 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projEstimate/QuoteTable/QuoteTableBody.tsx
> +  useEffect(() => console.log(touched, dirty ), [touched, dirty]);
よくないです。ありがとうございます。削除します。

2022-12-22 04:41 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projEstimate/hooks/useManipulateItems.tsx
> +  }, [setValues, rowIdx]);
そうですね！修正しました。確認ありがとうございます。

2022-12-26 00:08 UTC, Lorenzras commented
![](https://github.trello.services/images/mini-trello-icon.png) [見積：スピード改善](https://trello.com/c/Muf0Nf82/227-%E8%A6%8B%E7%A9%8D%EF%BC%9A%E3%82%B9%E3%83%94%E3%83%BC%E3%83%89%E6%94%B9%E5%96%84)

2022-12-26 01:15 UTC, RPA02coco approved these changes
確認しました！

2022-12-26 01:15 UTC, merged