introduction完了
Lorenzras/yumecoco-monorepo pull request #732
Opened 2023-10-16 08:46 UTC by kana-takahashi0705

## 変更

1. 変更内容

## 理由

1. 変更理由

## テスト

- 実行方法

2023-10-17 01:56 UTC, YokoHayakawa requested changes
変更内容を確認しました。
コメントを追加しましたので、ご確認をお願いします。

2023-10-17 01:56 UTC, YokoHayakawa commented on packages-kintone-customize/app-229-contracts/jsedit/api/calcFontSize.ts
> +
```suggestion
/**
 * 取得したテキストの幅を計算して、コンテナに収まるようにサイズを再調整する
 * @param {number} width コンテナ（セル）の幅（px、pt）
 * @param {string} text 表示する文字列
 * @returns number フォントサイズ
**/

```

1行目は関数の説明、@paramsは引数の説明になるため、記載位置の修正が必要かなと思いました。
「別ファイルにimportして調整したい部分を指定する。」については、関数というものに対する説明になってしまうので、ここでは不要です。

textの説明は必要に応じて修正してください。

2023-10-17 01:56 UTC, YokoHayakawa commented on packages-kintone-customize/app-229-contracts/jsedit/api/getAllStoresMeeting.ts
> +**/
```suggestion
/**
 * kintoneアプリより"meetingNumber"毎にソートした店舗情報を取得します
 * @returns 店舗情報の配列
**/
```

修正案を記載しましたので、ご確認をお願いします。
なお、返り値は店舗レコードの配列になります。

2023-10-17 01:56 UTC, YokoHayakawa commented on packages-kintone-customize/app-229-contracts/jsedit/api/getWeekDates.test.ts
> +  it('渡された年と月の週の範囲を確認する', () => {
```suggestion
  it('年と月に応じた週の範囲を返す', () => {
```
日本語の説明に誤解が生じそうかなと思いました。
ご確認をお願いします。

2023-10-17 01:56 UTC, YokoHayakawa commented on packages-kintone-customize/app-229-contracts/jsedit/api/getWeekDates.ts
> + * キャッシュを利用して週の曜日を取得計算する
計算はしていないので、関数の説明自体は変更前のままの方が分かりやすいかなと思いました。
ご確認をお願いします。

2023-11-06 07:22 UTC, Lorenzras approved these changes
OK!

2023-11-06 08:28 UTC, merged