入金用のアラート条件を変更します
Lorenzras/yumecoco-monorepo pull request #756
Opened 2023-10-25 04:34 UTC by YokoHayakawa

## 変更

1. アラート条件を"入金予定日を超過している請求書"へ変更する

## 理由

1. #751 より

## テスト

- 実行方法

2023-11-01 01:59 UTC, Lorenzras requested changes
コードを確認しました。

2023-11-01 01:59 UTC, Lorenzras commented on packages-automation/auto-paymentAlertV2/src/helpers/filterAPPaymentsToAlertTarget.ts
> +    if (expectedPaymentDate.value <= format(new Date(), 'yyyy-MM-dd')) {
`format`　はイテレーションごとに計算されます。
ループの外に移動した方が良いと思います。

2023-11-01 02:04 UTC, YokoHayakawa commented on packages-automation/auto-paymentAlertV2/src/helpers/filterAPPaymentsToAlertTarget.ts
> +    if (expectedPaymentDate.value <= format(new Date(), 'yyyy-MM-dd')) {
ご指摘ありがとうございます。
[d05fce5](https://github.com/Lorenzras/yumecoco-monorepo/pull/756/commits/d05fce59d0dc72035ae616ad7f2d8b704aea8b99)にて修正しましたので、ご確認をお願いします。

2023-11-02 00:50 UTC, Lorenzras approved these changes

2023-11-02 01:08 UTC, merged