契約金額の計算処理の修正
Lorenzras/yumecoco-monorepo pull request #814
Opened 2023-11-06 04:25 UTC by YokoHayakawa

## 変更

1. タイトルの通り

## 理由

1. 計算処理の共有化に伴い、汎用性を高めるため

## テスト

- getContractsSummary.test.ts(作成予定)

2023-11-06 09:14 UTC, Lorenzras requested changes
テストファイルまで作って、ありがとうございます！
コードを確認しました。

2023-11-07 06:49 UTC, Lorenzras requested changes
追加レビューです。よろしくお願い致します。

2023-11-07 06:49 UTC, Lorenzras commented on packages/api-kintone/src/contracts/getContractsSummary.ts
> +      }
ループ外で、計算した方が、処理速度にエコで、可読性がより上がると思います。以下のような感じです。

```typescript
  const result = // reduceループ省略

  result.追加金額税込 -= (result.減額Amt + result.返金Amt);
  result.合計受注金額税込 += result.追加金額税込 + result.契約金額税込;

  return result;
```

一応、既存のテストに合格すると思いますが、見落としているケースがあるかもしれません。
その時、教えて頂くとうれしいです。

2023-11-07 06:49 UTC, Lorenzras commented on packages/api-kintone/src/andpadProcurement/calculation/calcProfitability.ts
当面、変更不要。

リファクタリングの時、契約に関わる計算はgetContractSummaryに移行し、当関数にgetContractSummaryの結果をそのまま渡すこともありかもしれません。

2023-11-09 02:02 UTC, YokoHayakawa commented on packages/api-kintone/src/contracts/getContractsSummary.test.ts
> +    {// 本契約レコードを作成
目的は可読性の向上です。
テストファイルを作成する際に、本契約と追加契約のレコードの内容を書き換える処理において、
コードを見やすくするために追加しています。
あくまでも個人的な感覚でこの方が見やすいかなと思っています。
このままで良いのであれば、一旦このまま置いておこうかと思います。

2023-11-09 02:09 UTC, YokoHayakawa commented on packages/api-kintone/src/contracts/getContractsSummary.test.ts
> +    {// 本契約レコードを作成
目的は可読性の向上でしたが、下記コメントにてimmerパッケージのproduceに書き換えることにより、目的が達成できるため、修正しました。

2023-11-09 02:11 UTC, YokoHayakawa commented on packages/api-kintone/src/contracts/getContractsSummary.test.ts
> +    const formalContract = JSON.parse(JSON.stringify(contractDat));
ありがとうございます。
immerパッケージの存在を失念しておりました。
上記案を採用して修正しました。ご確認をお願いいたします。

2023-11-09 02:20 UTC, YokoHayakawa commented on packages/api-kintone/src/contracts/getContractsSummary.ts
> +      }
ご指摘ありがとうございます。
こちらで確認した限り、問題ないと思いますので、修正しました。
ご確認をお願いいたします。

2023-11-09 02:20 UTC, YokoHayakawa commented on packages/api-kintone/src/andpadProcurement/calculation/calcProfitability.ts
承知しました。

2023-11-10 06:36 UTC, Lorenzras requested changes

2023-11-10 06:36 UTC, merged