K246-契約一覧の出力の住所と金額を修正しました。
Lorenzras/yumecoco-monorepo pull request #820
Opened 2023-11-07 07:41 UTC by Lorenzras

## 変更

1. 郵便番号と住所をそれぞれの配列に分けました。
2. ついでに契約金額を修正しました。

## 理由

1. [変更理由](https://rdmuhwtt6gx7.cybozu.com/k/236/show#record=246)
2. `契約金額税込`は`追加契約`も入ってると思い込んでしまいました。現在、合算していますが、#814 はマージされたら、`合計契約金額`に変更します。

2023-11-09 02:56 UTC, YokoHayakawa requested changes
確認しました。
コメント残しましたので、確認をお願いいたします。

2023-11-09 02:56 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projProspectSearchV2/result/DownloadResult.tsx
> +        工事住所: d.projAddress || d.projAddressConfirmed,
```suggestion
        // K246 工事確定住所が入力されている工事は、工事確定住所を工事住所として表示してほしい
        工事郵便番号: d.projPostalCodeConfirmed ? d.projPostalCodeConfirmed :  d.projPostalCode,
        工事住所: d.projAddressConfirmed || d.projAddress,
```

工事確定住所は入力されている場合は、確定住所側が優先されるため、順番が逆ではないでしょうか。
認識違いがあれば教えてください。

2023-11-09 02:56 UTC, YokoHayakawa commented on packages/kokoas-client/src/pages/projSearch/sections/result/DownloadResult.tsx
> +        工事住所: d.projAddress || d.projAddressConfirmed,
```suggestion
        // K246 工事確定住所が入力されている工事は、工事確定住所を工事住所として表示してほしい
        工事郵便番号: d.projPostalCodeConfirmed? d.projPostalCodeConfirmed : d.projPostalCode,
        工事住所: d.projAddressConfirmed || d.projAddress,
```
上記コメントと同様です。
認識違いがあれば教えてください。

2023-11-09 23:59 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projProspectSearchV2/result/DownloadResult.tsx
> +        工事住所: d.projAddress || d.projAddressConfirmed,
日本語の認識が真逆でした。ｗ

ありがとうございます。

2023-11-09 23:59 UTC, Lorenzras commented on packages/kokoas-client/src/pages/projSearch/sections/result/DownloadResult.tsx
> +        工事住所: d.projAddress || d.projAddressConfirmed,
上記と同様でそのまま適用させて頂きました。

ありがとうございます。

2023-11-10 01:04 UTC, YokoHayakawa commented
@Lorenzras 
申し訳ありません、再開で問題ないです。
おそらくローカルでブランチ切り替える際に誤って消してしまっていたようです。

2023-11-10 01:07 UTC, YokoHayakawa approved these changes
修正を確認しました

2023-11-10 01:15 UTC, merged